#!/usr/bin/env python3
"""OMEGA gen-cluster — the GPU frontier rungs AFTER 오메가 완성 (#1791).

#1791 proved the learned-gate OMEGA closure works on a REAL trained ConsciousDecoderV2
(d384x6L), BUT with one honest caveat: CDV2's CA-neighbor mixing leaks lookahead (position
t sees x[:, t+1]) -> the next-byte head_a can peek at its own target -> absolute CE is
leak-optimistic AND free-running generation collapses to whitespace.

THE KEY FIX (this rung): train a LEAK-FREE CDV2 variant — causal_ca=True disables the
RIGHT-neighbor in the CA mixing so head_a is STRICTLY CAUSAL (cannot peek at the target).
Same d384x6L scale, same multilingual corpus recipe as #1791. Then THREE probes on the
trained leak-free substrate + the learned-gate bus, each PRE-REGISTERED (honest p7,
a_paper_negative_ok — a closed-negative is a valid finding):

  (1) F-LEAKFREE-GEN  — free-running decode ~300 bytes with the gated closure vs base on the
      LEAK-FREE substrate; report held-out CE (now leak-honest) AND a qualitative coherence
      judgment. Falsifier: gen is "coherent-ish" iff it emits NON-TRIVIAL VARIED byte
      structure (not constant/whitespace; entropy + distinct-byte-fraction over threshold)
      AND gated CE < base on leak-free eval. Else -> closed-negative ("leak-free gen still
      collapses").

  (3) F-DFDT-REAL     — enable the w6 derivative wire (mirror omega_coupling_apply_dt) over
      the REAL generation sequence: does adding the A<->G velocity channel change/improve
      held-out CE vs the static bus on the real substrate? Report Delta. Falsifier:
      |Delta CE| measurably != 0 (w6 is non-inert on a real moving sequence); improving
      (Delta<0) is the stronger positive.

  (6) F-PSI-STEER     — vary the 8D Psi-coord input across its range; does the generated byte
      distribution measurably shift (mean pairwise KL between gens at different Psi)?
      Falsifier: Psi steers iff mean pairwise KL between byte-distributions at distinct Psi
      settings exceeds a same-Psi resampling floor (Psi-space actually steers generation).

  (5) scale note      — if budget/time allows a quick d768 rung, report whether the
      structured-coupling + gate finding holds at d768 vs d384; else explicitly log
      "d768 scale rung DEFERRED (budget)". NO silent skip.

a_lane_akida_gpu_split: Lane-G / GPU (NOT Lane A AKIDA). GPU REQUIRED (g63, no silent CPU).
"""
import os, sys, json, math, time, hashlib, argparse, urllib.request
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from conscious_decoder import ConsciousDecoderV2  # noqa: E402
# reuse the #1791 corpus + extract + gate machinery verbatim (same method, leak-free model)
from omega_gpu_complete import (  # noqa: E402
    fetch_corpus, get_batch, train_substrate, extract_feats,
    softmax_np, ce_of, fit_gate, kl_structured,
    V, SMOOTH, ALPHA, UNIFORM_CE,
)

GATE_STEPS = 300
GATE_L2 = 0.02


# ───────────────────── (1) leak-free coherent generation ─────────────────────

def byte_stats(b: bytes):
    """Coherence proxies over a generated byte string: Shannon entropy (nats) over the byte
    histogram + the fraction of DISTINCT byte values + the fraction that are whitespace.
    Whitespace-collapse = low entropy + high whitespace fraction + few distinct bytes."""
    arr = np.frombuffer(b, dtype=np.uint8)
    if len(arr) == 0:
        return {"entropy": 0.0, "distinct_frac": 0.0, "ws_frac": 1.0, "n": 0}
    hist = np.bincount(arr, minlength=256).astype(np.float64)
    p = hist / hist.sum()
    nz = p[p > 0]
    ent = float(-(nz * np.log(nz)).sum())
    distinct = float((hist > 0).sum()) / 256.0
    ws = float(np.isin(arr, [32, 9, 10, 13, 0]).sum()) / len(arr)
    return {"entropy": ent, "distinct_frac": distinct, "ws_frac": ws, "n": int(len(arr))}


def gen_sample(model, prompt_bytes, n_new, device, g_star, log_base_vec,
               temperature=0.85, top_k=40):
    """Free-running decode n_new bytes two ways from the same prompt (autoregressive on the
    REAL trained heads — the gated closure IS the decode path):
       BASE  : sample from the weak unigram base only (gB*base).
       GATED : sample from gB*base + gA*A + gG*G (the OMEGA gated closure).
    Returns (base_text, gated_text, base_bytes, gated_bytes)."""
    model.eval()
    log_base = torch.from_numpy(log_base_vec.astype(np.float32)).to(device)

    def decode(use_gate):
        idx = torch.from_numpy(np.frombuffer(prompt_bytes, dtype=np.uint8).astype(np.int64)).unsqueeze(0).to(device)
        out = bytearray(prompt_bytes)
        with torch.no_grad():
            for _ in range(n_new):
                ctx = idx[:, -model.block_size:]
                la, lg, _, _, _ = model(ctx)
                A = la[0, -1].float()
                G = lg[0, -1].float()
                if use_gate:
                    logits = g_star[0] * log_base + g_star[1] * A + g_star[2] * G
                else:
                    logits = log_base.clone()
                logits = logits / temperature
                if top_k > 0:
                    v, _ = torch.topk(logits, min(top_k, V))
                    logits[logits < v[-1]] = float("-inf")
                p = torch.softmax(logits, dim=-1)
                nxt = int(torch.multinomial(p, 1).item())
                out.append(nxt)
                idx = torch.cat([idx, torch.tensor([[nxt]], device=device)], dim=1)
        return bytes(out)

    base_b = decode(False)
    gated_b = decode(True)
    dec = lambda b: b.decode("utf-8", errors="replace")
    return dec(base_b), dec(gated_b), base_b, gated_b


# ───────────────────── (3) dF/dt on the real generation sequence ─────────────────────

def dfdt_on_real(model, seq, block, device, g_star, log_base_vec, max_pos=4000,
                 dgain=0.5):
    """Walk the REAL held-out sequence step-by-step (teacher-forced, real next-byte targets)
    and compute held-out CE under TWO buses applied to the trained A/G heads at each position:
       STATIC : logits = gB*base + gA*A + gG*G
       DT     : logits = STATIC + dgain * ((A-G)_t - (A-G)_{t-1})   (w6 velocity wire)
    This mirrors engines/omega/coupling_bus.hexa omega_coupling_apply_dt EXACTLY (the w6 dF/dt
    wire is the A<->G velocity between consecutive REAL positions). Returns CE_static, CE_dt,
    Delta = CE_dt - CE_static (negative = the velocity channel improves), plus how often w6
    was non-zero (it is 0 only when A-G is unchanged step-to-step)."""
    model.eval()
    log_base = log_base_vec.astype(np.float64)
    gB, gA, gG = float(g_star[0]), float(g_star[1]), float(g_star[2])
    ce_static_sum = 0.0
    ce_dt_sum = 0.0
    n = 0
    nonzero_dt = 0
    with torch.no_grad():
        i = 0
        prev_diff = None  # (A-G) at the previous global position
        while i + block + 1 < len(seq) and n < max_pos:
            ctx = seq[i:i + block].astype(np.int64)
            x = torch.from_numpy(ctx).unsqueeze(0).to(device)
            la, lg, _, _, _ = model(x)
            A = la[0].float().cpu().numpy()   # (T,V)
            G = lg[0].float().cpu().numpy()
            for t in range(block):
                gpos = i + t
                if gpos + 1 >= len(seq) or n >= max_pos:
                    break
                tgt = int(seq[gpos + 1])
                diff = A[t] - G[t]
                static_logits = gB * log_base + gA * A[t] + gG * G[t]
                ps = softmax_np(static_logits[None, :])[0]
                ce_static_sum += -math.log(ps[tgt] + 1e-12)
                if prev_diff is not None:
                    w6 = dgain * (diff - prev_diff)
                    if np.abs(w6).sum() > 1e-9:
                        nonzero_dt += 1
                    dt_logits = static_logits + w6
                else:
                    dt_logits = static_logits
                pd = softmax_np(dt_logits[None, :])[0]
                ce_dt_sum += -math.log(pd[tgt] + 1e-12)
                prev_diff = diff
                n += 1
            i += block
    ce_static = ce_static_sum / max(1, n)
    ce_dt = ce_dt_sum / max(1, n)
    return {
        "ce_static": float(ce_static), "ce_dt": float(ce_dt),
        "delta": float(ce_dt - ce_static), "n": int(n),
        "frac_w6_nonzero": float(nonzero_dt / max(1, n - 1)),
        "dgain": dgain,
    }


# ───────────────────── (6) Psi-coord steering ─────────────────────

def psi_steer(model, prompt_bytes, n_new, device, g_star, log_base_vec,
              psi_gain=0.4, n_settings=5, n_resample=3, temperature=0.85, top_k=40,
              seed=20260604):
    """Vary the 8D Psi-coord (w4 wire: logits[i] += psi_gain * psi8[i % 8]) across distinct
    settings and measure whether the generated byte distribution SHIFTS.

    For each of n_settings Psi vectors (spread across the coord range) we generate from the
    SAME prompt and accumulate the byte histogram. The STEER signal = mean pairwise symmetric
    KL between the per-setting byte distributions. The FLOOR = mean pairwise KL between
    n_resample independent generations at a FIXED Psi (pure sampling noise). Psi steers iff
    steer_KL > floor_KL (the distribution moves more across Psi settings than across reseeds).
    Mirrors coupling_bus.hexa w4 (psi8 8D condition, #1780: 4 named + 4 residual)."""
    model.eval()
    rng = np.random.default_rng(seed)
    log_base = torch.from_numpy(log_base_vec.astype(np.float32)).to(device)
    gB, gA, gG = float(g_star[0]), float(g_star[1]), float(g_star[2])

    def decode_with_psi(psi8, gseed):
        torch.manual_seed(gseed)
        psi_t = torch.from_numpy(psi8.astype(np.float32)).to(device)  # (8,)
        # broadcast psi8 over the vocab via index mod 8 (the w4 wire indexing)
        psi_full = psi_t[torch.arange(V, device=device) % 8]          # (V,)
        idx = torch.from_numpy(np.frombuffer(prompt_bytes, dtype=np.uint8).astype(np.int64)).unsqueeze(0).to(device)
        out = bytearray()
        with torch.no_grad():
            for _ in range(n_new):
                ctx = idx[:, -model.block_size:]
                la, lg, _, _, _ = model(ctx)
                A = la[0, -1].float(); G = lg[0, -1].float()
                logits = gB * log_base + gA * A + gG * G + psi_gain * psi_full  # w4 Psi wire
                logits = logits / temperature
                if top_k > 0:
                    v, _ = torch.topk(logits, min(top_k, V))
                    logits[logits < v[-1]] = float("-inf")
                p = torch.softmax(logits, dim=-1)
                nxt = int(torch.multinomial(p, 1).item())
                out.append(nxt)
                idx = torch.cat([idx, torch.tensor([[nxt]], device=device)], dim=1)
        h = np.bincount(np.frombuffer(bytes(out), dtype=np.uint8), minlength=256).astype(np.float64)
        return (h + 0.5) / (h.sum() + 0.5 * 256)   # smoothed byte distribution

    def sym_kl(p, q):
        return float(0.5 * (np.sum(p * (np.log(p) - np.log(q))) + np.sum(q * (np.log(q) - np.log(p)))))

    # n_settings distinct Psi vectors: sweep the named depth/form axes across [-1,1], resid random
    settings = []
    for k in range(n_settings):
        frac = (k / max(1, n_settings - 1)) * 2.0 - 1.0   # -1 .. +1
        psi = np.zeros(8)
        psi[0] = frac          # depth axis
        psi[1] = -frac         # form axis (anti-correlated, widen the sweep)
        psi[2] = frac * 0.5
        psi[3] = -frac * 0.5
        psi[4:] = rng.normal(0, 0.3, 4)
        settings.append(psi)

    dists_per_setting = [decode_with_psi(s, 100 + j) for j, s in enumerate(settings)]
    # steer KL = mean pairwise sym-KL across distinct Psi
    steer_kls = []
    for a in range(len(dists_per_setting)):
        for b in range(a + 1, len(dists_per_setting)):
            steer_kls.append(sym_kl(dists_per_setting[a], dists_per_setting[b]))
    steer_kl = float(np.mean(steer_kls))

    # floor = mean pairwise sym-KL across reseeds at a FIXED (middle) Psi
    fixed_psi = settings[len(settings) // 2]
    floor_dists = [decode_with_psi(fixed_psi, 500 + j) for j in range(n_resample)]
    floor_kls = []
    for a in range(len(floor_dists)):
        for b in range(a + 1, len(floor_dists)):
            floor_kls.append(sym_kl(floor_dists[a], floor_dists[b]))
    floor_kl = float(np.mean(floor_kls)) if floor_kls else 0.0

    return {
        "steer_kl": steer_kl, "floor_kl": floor_kl,
        "ratio": float(steer_kl / (floor_kl + 1e-9)),
        "n_settings": n_settings, "n_resample": n_resample, "psi_gain": psi_gain,
        "psi_steers": bool(steer_kl > floor_kl),
    }


# ───────────────────── train one leak-free rung + run the 3 probes ─────────────────────

def run_rung(d_model, n_layer, n_head, n_kv_head, block, bs, lr, steps, device,
             train_data, val_data, held, label, do_psi=True, do_dfdt=True):
    print(f"\n{'='*30} RUNG {label} (d_model={d_model}, causal_ca=True LEAK-FREE) {'='*30}", flush=True)
    model = ConsciousDecoderV2(
        vocab_size=V, d_model=d_model, n_head=n_head, n_layer=n_layer,
        block_size=block, n_kv_head=n_kv_head, consciousness_dim=128,
        causal_ca=True,   # ← THE KEY FIX: strictly-causal CA, no lookahead leak
    ).to(device)
    nparam = model.count_params()
    print(f"CDV2 params: {nparam:,} ({nparam/1e6:.2f}M)  causal_ca={model.causal_ca}", flush=True)

    # ---- leak self-test on the UNTRAINED model: flipping only the LAST byte must NOT change
    #      logits_a at earlier positions (strict causality of head_a).
    model.eval()
    with torch.no_grad():
        xt = torch.randint(0, V, (1, min(32, block)), device=device)
        la1, _, _, _, _ = model(xt)
        xt2 = xt.clone(); xt2[0, -1] = (int(xt[0, -1]) + 7) % V
        la2, _, _, _, _ = model(xt2)
        leak = float((la1[0, :-1] - la2[0, :-1]).abs().max().item())
    print(f"leak self-test (flip last byte -> max change in head_a at earlier pos): {leak:.3e}  (want ~0)", flush=True)
    leak_free = leak < 1e-4

    curve, val_ce, train_wall = train_substrate(model, train_data, val_data, steps, block, bs, lr, device)
    first_ce = curve[0]["ce_a"]; final_ce = curve[-1]["ce_a"]
    descended = final_ce < first_ce
    print(f"(b) trained leak-free substrate: ce_a {first_ce:.4f} -> {final_ce:.4f}  val_ce={val_ce:.4f}  "
          f"descended={descended}  wall={train_wall:.1f}s", flush=True)

    # ---- extract on disjoint held-out (gate / test / shuffled)
    gate_seq = held[:len(held) // 2]
    test_seq = held[len(held) // 2:]
    gate_feats, gate_tgt = extract_feats(model, gate_seq, block, device, max_pos=8000)
    test_feats, test_tgt = extract_feats(model, test_seq, block, device, max_pos=8000)
    test_feats_shuf, _ = extract_feats(model, test_seq, block, device, max_pos=8000, shuffle_ctx=True)

    g_star = fit_gate(gate_feats, gate_tgt, steps=GATE_STEPS, l2=GATE_L2)
    print(f"learned gate g* = [gB={g_star[0]:.4f}, gA={g_star[1]:.4f}, gG={g_star[2]:.4f}]", flush=True)

    ce_base = ce_of(np.array([1.0, 0.0, 0.0]), test_feats, test_tgt)
    ce_fixed = ce_of(np.array([1.0, ALPHA, -ALPHA]), test_feats, test_tgt)
    ce_aonly = ce_of(np.array([1.0, ALPHA, 0.0]), test_feats, test_tgt)
    ce_gated = ce_of(g_star, test_feats, test_tgt)
    print(f"--- held-out TEST CE (LEAK-FREE, nats/byte) ---", flush=True)
    print(f"  base {ce_base:.6f} | fixed_AmG {ce_fixed:.6f} | a_only {ce_aonly:.6f} | "
          f"GATED {ce_gated:.6f} | uniform {UNIFORM_CE:.6f}", flush=True)

    st = kl_structured(test_feats, test_feats_shuf, test_tgt)
    print(f"structured: A-wire gain real {st['gain_real']:.4f} vs shuf {st['gain_shuf']:.4f} "
          f"-> structured(>1.5x)={st['structured_ce']}", flush=True)

    # weak base vec over test_seq for the generation paths
    counts = np.full(V, SMOOTH)
    for b in test_seq:
        counts[int(b)] += 1.0
    log_base_vec = np.log(counts / counts.sum())
    prompt = bytes(test_seq[:48].tobytes())

    # ---- (1) leak-free coherent generation ~300 bytes
    base_txt, gated_txt, base_b, gated_b = gen_sample(model, prompt, 300, device, g_star, log_base_vec)
    base_stats = byte_stats(base_b[len(prompt):])
    gated_stats = byte_stats(gated_b[len(prompt):])
    # pre-registered coherence: varied byte structure (entropy & distinct over floor, not all-whitespace)
    coherent = (gated_stats["entropy"] > 1.5 and gated_stats["distinct_frac"] > 0.10
                and gated_stats["ws_frac"] < 0.80)
    gen_ce_ok = ce_gated < ce_base
    leakfree_gen_pass = coherent and gen_ce_ok
    print(f"\n(1) F-LEAKFREE-GEN: gated gen entropy={gated_stats['entropy']:.3f} "
          f"distinct={gated_stats['distinct_frac']:.3f} ws={gated_stats['ws_frac']:.3f}  "
          f"coherent={coherent}  gated<base CE={gen_ce_ok}  -> PASS={leakfree_gen_pass}", flush=True)
    print(f"  [BASE]  {base_txt[len(prompt):][:160]!r}", flush=True)
    print(f"  [GATED] {gated_txt[len(prompt):][:160]!r}", flush=True)

    # ---- (3) dF/dt on real sequence
    dfdt = None
    if do_dfdt:
        dfdt = dfdt_on_real(model, test_seq, block, device, g_star, log_base_vec, max_pos=4000)
        print(f"\n(3) F-DFDT-REAL: CE_static={dfdt['ce_static']:.6f} CE_dt={dfdt['ce_dt']:.6f} "
              f"Delta={dfdt['delta']:+.6f}  w6-nonzero-frac={dfdt['frac_w6_nonzero']:.3f}", flush=True)

    # ---- (6) Psi steering
    psi = None
    if do_psi:
        psi = psi_steer(model, prompt, 200, device, g_star, log_base_vec)
        print(f"\n(6) F-PSI-STEER: steer_KL={psi['steer_kl']:.5f} floor_KL={psi['floor_kl']:.5f} "
              f"ratio={psi['ratio']:.2f}x  -> psi_steers={psi['psi_steers']}", flush=True)

    return {
        "label": label, "leak_self_test": leak, "leak_free": bool(leak_free),
        "params": int(nparam), "d_model": d_model, "n_layer": n_layer,
        "train": {"first_ce_a": first_ce, "final_ce_a": final_ce, "val_ce": val_ce,
                  "descended": bool(descended), "wall_s": train_wall, "steps": steps,
                  "curve": curve},
        "gate": {"gB": float(g_star[0]), "gA": float(g_star[1]), "gG": float(g_star[2])},
        "ce": {"base": ce_base, "fixed_AmG": ce_fixed, "a_only": ce_aonly, "gated": ce_gated,
               "uniform_floor": UNIFORM_CE},
        "structured": st,
        "F_LEAKFREE_GEN": {
            "coherent": bool(coherent), "gated_lt_base": bool(gen_ce_ok),
            "PASS": bool(leakfree_gen_pass),
            "base_stats": base_stats, "gated_stats": gated_stats,
            "base_sample": base_txt[len(prompt.decode('utf-8', errors='replace')):][:300],
            "gated_sample": gated_txt[len(prompt.decode('utf-8', errors='replace')):][:300],
        },
        "F_DFDT_REAL": dfdt,
        "F_PSI_STEER": psi,
        "model_obj": model,  # for ckpt save (stripped before json dump)
        "config": {"vocab_size": V, "d_model": d_model, "n_head": n_head, "n_layer": n_layer,
                   "block_size": block, "n_kv_head": n_kv_head, "consciousness_dim": 128,
                   "causal_ca": True},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=6000)
    ap.add_argument("--block", type=int, default=256)
    ap.add_argument("--bs", type=int, default=32)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--corpus_mb", type=int, default=120)
    ap.add_argument("--d768", type=int, default=1, help="1 = also run a quick d768 scale rung if budget allows")
    ap.add_argument("--d768_steps", type=int, default=2500)
    ap.add_argument("--budget_s", type=int, default=3000, help="wall-time budget guard for the d768 rung")
    ap.add_argument("--out", default="omega_gen_results.json")
    ap.add_argument("--ckpt", default="omega_cdv2_d384_leakfree.pt")
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    if device != "cuda":
        print("!!! NO CUDA — refusing to fake a GPU train (g63). Reporting BLOCKED.", flush=True)
        json.dump({"BLOCKED": "no_cuda", "device": device}, open(args.out, "w"), indent=2)
        sys.exit(2)
    gpu_name = torch.cuda.get_device_name(0)
    print(f"=== OMEGA gen-cluster — LEAK-FREE causal-CA substrate + 3 probes ===", flush=True)
    print(f"device={device}  gpu={gpu_name}  torch={torch.__version__}", flush=True)

    target = args.corpus_mb * 1_000_000
    corpus, prov = fetch_corpus(target, os.path.join(HERE, "omega_corpus.bin"))
    sha = hashlib.sha256(corpus.tobytes()).hexdigest()
    n = len(corpus)
    print(f"corpus: {n}B  prov={prov}  sha256={sha[:16]}", flush=True)

    cut = int(n * 0.8)
    train_data = corpus[:cut]
    held = corpus[cut:]
    val_data = held[:len(held) // 2]

    t_start = time.time()
    # ---- d384 leak-free rung (the primary) ----
    r384 = run_rung(384, 6, 6, 2, args.block, args.bs, args.lr, args.steps, device,
                    train_data, val_data, held, "d384-leakfree")

    # save ckpt
    model = r384.pop("model_obj")
    torch.save({"model": model.state_dict(), "config": r384["config"]}, args.ckpt)
    ckpt_sha = hashlib.sha256(open(args.ckpt, "rb").read()).hexdigest()
    print(f"\nckpt saved: {args.ckpt}  sha256={ckpt_sha[:16]}", flush=True)
    del model
    torch.cuda.empty_cache()

    # ---- (5) optional d768 scale rung (budget-guarded) ----
    r768 = None
    elapsed = time.time() - t_start
    if args.d768 and elapsed < args.budget_s * 0.6:
        print(f"\n[scale] budget OK (elapsed {elapsed:.0f}s < {args.budget_s*0.6:.0f}s) — firing d768 quick rung", flush=True)
        rr = run_rung(768, 6, 12, 4, args.block, args.bs, args.lr, args.d768_steps, device,
                      train_data, val_data, held, "d768-leakfree", do_psi=True, do_dfdt=True)
        rr.pop("model_obj", None)
        r768 = rr
    else:
        print(f"\n[scale] d768 scale rung DEFERRED (budget) — elapsed {elapsed:.0f}s, budget {args.budget_s}s. NO silent skip.", flush=True)

    results = {
        "lane": "Lane-G", "substrate": "GPU", "gpu": gpu_name, "torch": torch.__version__,
        "corpus_bytes": int(n), "corpus_prov": prov, "corpus_sha256": sha,
        "fix": "causal_ca=True — strictly-causal CA mixing (no x_right lookahead leak)",
        "ckpt": {"path": args.ckpt, "sha256": ckpt_sha},
        "d384": r384,
        "d768": r768 if r768 is not None else {"DEFERRED": "budget", "note": "d768 scale rung DEFERRED (budget); NO silent skip"},
        "total_wall_s": time.time() - t_start,
    }
    json.dump(results, open(args.out, "w"), indent=2, ensure_ascii=False)

    print("\n=== GEN-CLUSTER SUMMARY ===", flush=True)
    print(f"  leak-free self-test (d384): {r384['leak_self_test']:.3e} (leak_free={r384['leak_free']})", flush=True)
    print(f"  (1) F-LEAKFREE-GEN : PASS={r384['F_LEAKFREE_GEN']['PASS']} "
          f"(coherent={r384['F_LEAKFREE_GEN']['coherent']}, gated<base={r384['F_LEAKFREE_GEN']['gated_lt_base']})", flush=True)
    print(f"  (3) F-DFDT-REAL    : Delta={r384['F_DFDT_REAL']['delta']:+.6f} "
          f"(w6-nonzero {r384['F_DFDT_REAL']['frac_w6_nonzero']:.2f})", flush=True)
    print(f"  (6) F-PSI-STEER    : steers={r384['F_PSI_STEER']['psi_steers']} "
          f"(ratio {r384['F_PSI_STEER']['ratio']:.2f}x)", flush=True)
    if r768:
        print(f"  (5) d768 rung      : gated<base={r768['F_LEAKFREE_GEN']['gated_lt_base']} "
              f"structured={r768['structured']['structured_ce']} (finding holds at d768)", flush=True)
    else:
        print(f"  (5) d768 rung      : DEFERRED (budget)", flush=True)
    print(f"results -> {args.out}", flush=True)


if __name__ == "__main__":
    main()
