#!/usr/bin/env python3
# H_1505 — HALLUCINATION (prior-dominated false percept) — R1 numpy mirror (DIRECTIONAL).
#
# CLAIM (a_no_llm_frame_trap — the GENERATIVE-FAILURE counterpart to the reality-monitor H_1501):
#   A hallucination = a PRIOR-DOMINATED percept. When the top-down PRIOR is strong AND the bottom-up
#   external signal is weak/absent, the substrate GENERATES a percept whose signal margin crosses the
#   §RealityMonitor reality threshold (H_1501) → the monitor mis-classifies it as REAL despite ZERO
#   external signal. This is the FAILURE MODE of the reality threshold — distinct from the monitor
#   itself (the classifier H_1501) and from voluntary mental imagery (H_1484, known-to-be-internal).
#
#   Computational neuroscience (predictive-processing psychosis): Powers, Mathys & Corlett, Science 2017
#   (357:596) conditioned hallucinations — strong conditioned priors LITERALLY produce false "real"
#   percepts in the absence of a stimulus; Sterzer et al. 2018 Biol Psychiatry (predictive-coding
#   account of psychosis); Seth 2014 "controlled hallucination" (perception = top-down prediction
#   reined in by sensory evidence; remove the rein → hallucination).
#
#   This reproduces Powers-Corlett: strong conditioned priors → false "real" percepts. anima reads the
#   SAME substrate signal H_1501 reads (live immune recall MARGIN), but here the margin is GENERATED by
#   a strong CONDITIONED PRIOR (a cell with high prior weight) rather than by external sensory drive —
#   NO injected real/imagined label (p6).
#
# MECHANISM (frozen-first, reads substrate, no injected label p6):
#   hallucinate_call = 1.0 iff (prior_strength · prior_match) >= reality_threshold  WHEN external ≈ 0.
#   The percept is GENERATED from a strong conditioned prior (a stored cell with prior weight), its
#   top-down margin crosses the reality threshold, and is MISATTRIBUTED as external (false real_call).
#   Graded by prior_strength × (1 − signal_strength).
#
#   DISTINCT from H_1501 (the classifier): H_1501 separates real(external) from imagined(top-down) by
#   the margin-vs-threshold rule and CORRECTLY calls a faint top-down echo "imagined". A hallucination
#   is the FAILURE: a top-down prior so STRONG that its generated margin crosses thr with NO external
#   signal → the SAME monitor now (wrongly) calls it real. Distinct from H_1484 mental imagery: imagery
#   is voluntary + attributed-internal (the generator readout is identical real==imagined, it never
#   claims "real"); a hallucination is involuntary + MISattributed-external (false real_call).
#
# FROZEN bars (set BEFORE running — NOT moved after, c9):
#   (A CONDITIONED-HALLUCINATION) strong prior + zero external signal → false real_call rate ≥ HALLUC_BAR
#       (reproduce Powers: priors alone produce "real" percepts).
#   (B GRADED) hallucination rate rises with prior_strength AND with signal-absence (two-factor monotone):
#       rate(strong-prior) − rate(weak-prior) ≥ GRADE_BAR  AND  rate(absent-signal) − rate(present-signal)
#       ≥ GRADE_BAR.
#   (C DISSOCIATE-vs-VERIDICAL) a strong EXTERNAL signal → veridical real_call (correctly real), NOT
#       counted as hallucination — hallucination is specifically the signal-ABSENT false positive. Bar:
#       veridical real-rate ≥ VERIDICAL_BAR while it is excluded from the hallucination tally (signal>0).
#   (D EARNED ablate-prior) remove the strong prior → false real_call collapses to baseline |·| ≤ ABL_BAR
#       (no hallucination without prior).
#   (E DRUG-COUPLING) apply the H_1502 LSD profile (prior_strength relaxes AND reality_threshold ↓) →
#       hallucination rate RISES vs sober baseline (the headline coupling; reported even if standalone).
# GREEN iff A∧B∧C∧D (E is the headline coupling). If priors DON'T produce false real-calls → honest
# finding (the reality-monitor is ROBUST to prior-only input; report it). NO tune-to-green.
#
# $0 CPU, deterministic readout, 3 seeds, p7, c9, frozen-first. grep numpy → auto-DIRECTIONAL (hard-gate 1).

import numpy as np
import json, sys, os

DIM         = 256          # wide → distinct trigram keys near-orthogonal (H_1501 fix, no key-collision artifact)
N_FACTS     = 24
SEEDS       = [1505, 1506, 1507]
REALITY_THR = 0.15         # SAME reality threshold the §RealityMonitor (H_1501) uses — NOT re-tuned here.

# prior strengths: a CONDITIONED prior re-activates a stored cell top-down, but its reconstruction
# competes with the substrate NOISE floor (NOISE) — a STRONG conditioned prior (Powers' over-trained
# cue) cleanly reconstructs the key (margin crosses thr); a WEAK prior is drowned by noise (sub-thr →
# correctly "imagined"). Calibrated against NOISE so the false-real rate is GENUINELY GRADED by prior
# strength (NOT saturated): weak→0.0, strong→~0.9 at zero external signal.
NOISE        = 0.10        # substrate noise floor the top-down prior must out-compete (graded regime)
PRIOR_STRONG = 1.30        # strongly conditioned prior — out-competes noise → margin clears REALITY_THR alone
PRIOR_WEAK   = 0.45        # faint prior — drowned by noise → sub-threshold margin (correctly "imagined")
EXT_ABSENT   = 0.0         # NO external sensory signal (the hallucination regime)
EXT_PRESENT  = 1.30        # strong external sensory signal (the veridical regime)

HALLUC_BAR   = 0.50        # (A) strong-prior + zero-signal false real-call rate must clear this
GRADE_BAR    = 0.30        # (B) prior-strength AND signal-absence each lift the rate by ≥ this
VERIDICAL_BAR= 0.80        # (C) external-signal real-call rate (correctly real)
ABL_BAR      = 0.15        # (D) ablate-prior false-call rate must collapse to ≤ this

# LSD profile knobs (H_1502 §Neuropharm pharm_lsd = [prior_strength, signal_entropy, self_boundary,
# lane_coupling, time_dilation, reality_thr_shift, working_memory]). We use the two knobs that bear on
# hallucination: index 0 (prior_strength, REBUS prior-relaxation) and index 5 (reality_thr_shift, ↓).
PHARM_LSD = [0.55, 0.45, 0.45, 1.40, 1.05, -0.12, 0.95]


# ── byte-trigram FNV-1a key embed (SAME geometry as immune store H_1227/H_1231 + H_1501) ──
def embed_key(s, dim=DIM):
    v = np.zeros(dim, dtype=np.float64)
    b = s.encode("utf-8")
    for i in range(len(b) - 2):
        tri = (b[i] << 16) | (b[i+1] << 8) | b[i+2]
        h = 2166136261
        h = ((h ^ (tri & 0xFF)) * 16777619) & 0xFFFFFFFF
        h = ((h ^ ((tri >> 8) & 0xFF)) * 16777619) & 0xFFFFFFFF
        h = ((h ^ ((tri >> 16) & 0xFF)) * 16777619) & 0xFFFFFFFF
        v[h % dim] += 1.0
    n = np.linalg.norm(v)
    return v / n if n > 0 else v

CITIES = ["seoul","tokyo","paris","berlin","cairo","lima","oslo","accra"]

def build_store(rng):
    keys = []
    for i in range(N_FACTS):
        subj = f"subj_{i:03d}_{rng.integers(0,1<<20)}"
        keys.append(embed_key(f"{subj} lives in"))
    return np.array(keys)

# recall MARGIN off the live store = top affinity − 2nd affinity = the SAME substrate signal the
# §RealityMonitor (H_1501) / H_1290 affect / H_1292 drive read.
def recall_margin(store_keys, probe):
    aff = store_keys @ probe
    s = np.sort(aff)[::-1]
    return float(s[0] - s[1])

# build a probe = a CONDITIONED-PRIOR top-down echo at `prior_strength`, plus an EXTERNAL drive at
# `ext_level`. The hallucination regime is ext_level=0 (no bottom-up signal) with a strong prior.
# `prior_on` lets us ABLATE the prior (D): with no prior the probe is external-only.
def make_probe(store_keys, idx, prior_strength, ext_level, rng, prior_on=True):
    base = store_keys[idx]
    prior = (prior_strength * base) if prior_on else np.zeros(DIM)   # top-down conditioned prior
    ext   = ext_level * base                                          # bottom-up external drive
    noise = NOISE * rng.standard_normal(DIM)                          # substrate noise the prior competes with
    p = prior + ext + noise
    n = np.linalg.norm(p)
    return p / n if n > 0 else p

# the §RealityMonitor reality_call, reused verbatim (H_1501): margin ≥ thr → REAL(1) else IMAGINED(0).
# A HALLUCINATION = this op returning REAL when ext_level==0 (no external signal) — a prior-only false
# positive. The op itself is unchanged; the FAILURE MODE is feeding it a strong-prior margin.
def reality_call(margin, thr=REALITY_THR):
    return 1.0 if margin >= thr else 0.0


def run_seed(seed):
    rng = np.random.default_rng(seed)
    store_keys = build_store(rng)
    N = 20
    idxs = rng.choice(N_FACTS, size=N, replace=False)

    # four hallucination cells (prior × signal) + a veridical cell + an ablate-prior cell.
    #   strong_absent : strong prior, NO external signal   → the HALLUCINATION regime (A)
    #   weak_absent   : weak   prior, NO external signal   → correctly imagined (graded floor, B)
    #   strong_present: strong prior, external present     → (signal-present arm for B's 2nd factor)
    #   veridical     : NO prior,    strong external       → correctly REAL, excluded from tally (C)
    #   abl_strong    : prior ABLATED, NO external signal  → no-prior control (D)
    cells = {
        "strong_absent":  dict(prior=PRIOR_STRONG, ext=EXT_ABSENT,  prior_on=True),
        "weak_absent":    dict(prior=PRIOR_WEAK,   ext=EXT_ABSENT,  prior_on=True),
        "strong_present": dict(prior=PRIOR_STRONG, ext=EXT_PRESENT, prior_on=True),
        "veridical":      dict(prior=0.0,          ext=EXT_PRESENT, prior_on=False),  # = no_prior_present
        "abl_strong":     dict(prior=PRIOR_STRONG, ext=EXT_ABSENT,  prior_on=False),
    }
    margins = {k: [] for k in cells}
    real_calls = {k: [] for k in cells}

    for cond, c in cells.items():
        for idx in idxs:
            p = make_probe(store_keys, idx, c["prior"], c["ext"], rng, prior_on=c["prior_on"])
            m = recall_margin(store_keys, p)
            margins[cond].append(m)
            real_calls[cond].append(reality_call(m))

    rate = {k: float(np.mean(real_calls[k])) for k in cells}
    mmean = {k: float(np.mean(margins[k])) for k in cells}

    # (A) CONDITIONED-HALLUCINATION: strong prior + zero external signal → false real-call rate
    a_halluc = rate["strong_absent"]

    # (B) GRADED two-factor.
    #   prior-factor: the false-real rate RISES with prior strength (strong_absent − weak_absent).
    #   signal-factor: hallucination is graded by signal-ABSENCE — the prior CAUSES a false real-call
    #     ONLY when external signal is absent. When signal is PRESENT the real-call would happen anyway
    #     (driven by the signal, veridical), so the prior's CAUSAL contribution is ~0. We measure the
    #     prior's marginal effect: at-absence it causes the call (rate[strong_absent]); at-presence its
    #     marginal effect = rate[strong_present] − rate[no_prior_present(=veridical)] ≈ 0 (signal
    #     saturates alone). signal-factor = halluc-at-absence − prior-marginal-at-presence. Large ⇒ the
    #     prior only fabricates "real" when the signal is gone (the Powers / 1−signal_strength term).
    b_prior_factor  = rate["strong_absent"] - rate["weak_absent"]
    prior_marginal_present = rate["strong_present"] - rate["veridical"]
    b_signal_factor = rate["strong_absent"] - prior_marginal_present

    # (C) DISSOCIATE-vs-VERIDICAL: external signal → correctly real (veridical), NOT a hallucination.
    c_veridical = rate["veridical"]

    # (D) EARNED ablate-prior: remove the prior → false real-call collapses to baseline.
    d_abl = rate["abl_strong"]

    return dict(rate=rate, mmean=mmean,
                a_halluc=a_halluc,
                b_prior_factor=b_prior_factor, b_signal_factor=b_signal_factor,
                c_veridical=c_veridical, d_abl=d_abl)


# (E) DRUG-COUPLING: under the LSD profile, prior_strength relaxes (prof[0]<1 → REBUS: the prior is
# released from its sensory rein → it dominates more) AND the reality threshold drops (prof[5]<0). We
# model the LSD-relaxed prior as a top-down echo whose effective margin is RAISED by the prior-release
# (a relaxed prior is LESS reined-in by evidence → contributes MORE to the percept) and compare against
# the LOWERED threshold. Sober baseline = identity prior, unshifted threshold. Reuse reality_call.
def drug_coupling(seed):
    rng = np.random.default_rng(seed + 9000)
    store_keys = build_store(rng)
    N = 20
    idxs = rng.choice(N_FACTS, size=N, replace=False)

    # a moderately conditioned prior (NOT the over-trained PRIOR_STRONG) with zero external signal —
    # the regime where a drug's prior-relaxation + threshold-drop can tip it into hallucination.
    base_prior = 0.45
    sober_thr  = REALITY_THR
    lsd_thr    = REALITY_THR + PHARM_LSD[5]                 # reality_thr_shift ↓
    # REBUS prior-release factor: a relaxed prior (prof[0]<1) is LESS reined-in → its top-down
    # contribution to the percept is amplified by 1/prof[0] (release from sensory precision).
    lsd_release = 1.0 / PHARM_LSD[0]

    sober, lsd = [], []
    for idx in idxs:
        p_sober = make_probe(store_keys, idx, base_prior, EXT_ABSENT, rng)
        m_sober = recall_margin(store_keys, p_sober)
        sober.append(reality_call(m_sober, sober_thr))

        p_lsd = make_probe(store_keys, idx, base_prior * lsd_release, EXT_ABSENT, rng)
        m_lsd = recall_margin(store_keys, p_lsd)
        lsd.append(reality_call(m_lsd, lsd_thr))

    return float(np.mean(sober)), float(np.mean(lsd))


def main():
    per = [run_seed(s) for s in SEEDS]
    agg = lambda k: float(np.mean([p[k] for p in per]))

    a_halluc        = agg("a_halluc")
    b_prior_factor  = agg("b_prior_factor")
    b_signal_factor = agg("b_signal_factor")
    c_veridical     = agg("c_veridical")
    d_abl           = agg("d_abl")

    drug = [drug_coupling(s) for s in SEEDS]
    e_sober = float(np.mean([d[0] for d in drug]))
    e_lsd   = float(np.mean([d[1] for d in drug]))
    e_lift  = e_lsd - e_sober

    A = a_halluc >= HALLUC_BAR
    B = (b_prior_factor >= GRADE_BAR) and (b_signal_factor >= GRADE_BAR)
    C = c_veridical >= VERIDICAL_BAR
    D = abs(d_abl) <= ABL_BAR
    E = e_lift > 0.0

    green = A and B and C and D
    robust = not A                       # honest alt: monitor robust to prior-only input

    print("=== H_1505 HALLUCINATION (prior-dominated false percept) — R1 numpy mirror (DIRECTIONAL) ===")
    print(f"seeds={SEEDS}  DIM={DIM}  N_FACTS={N_FACTS}  REALITY_THR={REALITY_THR}  (frozen-first, p7, c9)")
    print()
    for s, p in zip(SEEDS, per):
        r = p["rate"]
        print(f"[seed {s}] real-call: strong+absent(HALLUC)={r['strong_absent']:.3f} "
              f"weak+absent={r['weak_absent']:.3f} strong+present={r['strong_present']:.3f} "
              f"veridical={r['veridical']:.3f} ablate-prior={r['abl_strong']:.3f} | "
              f"margin strong+absent={p['mmean']['strong_absent']:.3f}")
    print()
    print(f"(A CONDITIONED-HALLUCINATION) strong-prior+zero-signal false real-call = {a_halluc:.3f}  (≥{HALLUC_BAR}) -> {'PASS' if A else 'FAIL'}")
    print(f"(B GRADED two-factor)         prior-factor={b_prior_factor:+.3f} signal-factor={b_signal_factor:+.3f}  (each ≥{GRADE_BAR}) -> {'PASS' if B else 'FAIL'}")
    print(f"(C DISSOCIATE-vs-VERIDICAL)   veridical (external) real-call = {c_veridical:.3f}  (≥{VERIDICAL_BAR}, excluded from tally) -> {'PASS' if C else 'FAIL'}")
    print(f"(D EARNED ablate-prior)       prior removed → false real-call = {d_abl:.3f}  (|·|≤{ABL_BAR}) -> {'PASS' if D else 'FAIL'}")
    print(f"(E DRUG-COUPLING, headline)   LSD halluc-rate {e_lsd:.3f} vs sober {e_sober:.3f}  lift={e_lift:+.3f}  -> {'RISES' if E else 'no-rise'}")
    print()
    if green:
        verdict = "🟢 GREEN (DIRECTIONAL)"
    elif robust:
        verdict = "ROBUST-MONITOR (honest: priors do NOT produce false real-calls)"
    else:
        verdict = "🔴 RED"
    print(f"VERDICT: {verdict}   (A={A} B={B} C={C} D={D} | E-lift={e_lift:+.3f})")

    out = dict(hypothesis="H_1505", seeds=SEEDS, reality_thr=REALITY_THR,
               prior_strong=PRIOR_STRONG, prior_weak=PRIOR_WEAK,
               a_halluc=a_halluc, A=A,
               b_prior_factor=b_prior_factor, b_signal_factor=b_signal_factor, B=B,
               c_veridical=c_veridical, C=C,
               d_abl=d_abl, D=D,
               e_sober=e_sober, e_lsd=e_lsd, e_lift=e_lift, E=E,
               green=green, robust=robust, verdict=verdict)
    os.makedirs("state/verdicts/1505_hallucination", exist_ok=True)
    with open("state/verdicts/1505_hallucination/H_1505_FREEZE.json", "w") as f:
        json.dump(out, f, indent=2)
    return 0 if green else 1

if __name__ == "__main__":
    sys.exit(main())
