// Generated by HEXA self-host compiler
#include "runtime.h"

HexaVal abs_d(HexaVal x);
HexaVal max_abs_diff(HexaVal c1, HexaVal c2, HexaVal n);
HexaVal lcg_fill(HexaVal h, HexaVal n, HexaVal seed0);
HexaVal u_main(void);


static HexaVal __hexa_sl_0;
static HexaVal __hexa_sl_1;
static HexaVal __hexa_sl_2;
static HexaVal __hexa_sl_3;
static HexaVal __hexa_sl_4;
static HexaVal __hexa_sl_5;
static HexaVal __hexa_sl_6;
static HexaVal __hexa_sl_7;
static HexaVal __hexa_sl_8;
static HexaVal __hexa_sl_9;
static HexaVal __hexa_sl_10;
static HexaVal __hexa_sl_11;
static HexaVal __hexa_sl_12;
static HexaVal __hexa_sl_13;
static HexaVal __hexa_sl_14;
static HexaVal __hexa_sl_15;
static HexaVal __hexa_sl_16;
static HexaVal __hexa_sl_17;
static HexaVal __hexa_sl_18;
static HexaVal __hexa_sl_19;
static HexaVal __hexa_sl_20;
static HexaVal __hexa_sl_21;
static HexaVal __hexa_sl_22;
static HexaVal __hexa_sl_23;
static HexaVal __hexa_sl_24;
static HexaVal __hexa_sl_25;
static HexaVal __hexa_sl_26;
static HexaVal __hexa_sl_27;
static HexaVal __hexa_sl_28;
static HexaVal __hexa_sl_29;
static void __hexa_strlit_init(void) {
    __hexa_sl_0 = hexa_str("PASS  F-RFC040-GPU-AVAIL  cuda_available=1 device_count=");
    __hexa_sl_1 = hexa_str(" (real CUDA host)");
    __hexa_sl_2 = hexa_str("FAIL  F-RFC040-GPU-AVAIL  avail=");
    __hexa_sl_3 = hexa_str(" count=");
    __hexa_sl_4 = hexa_str(" (expected 1 / >=1 on CUDA host)");
    __hexa_sl_5 = hexa_str("PASS  F-RFC040-GPU-TODEVICE  farr_to_device=1 farr_to_host=1 round-trip exact (real H2D/D2H)");
    __hexa_sl_6 = hexa_str("FAIL  F-RFC040-GPU-TODEVICE  to_dev=");
    __hexa_sl_7 = hexa_str(" to_hst=");
    __hexa_sl_8 = hexa_str(" W[3]=");
    __hexa_sl_9 = hexa_str("FAIL  F-RFC040-GPU-EQUIV-SMALL  farr_matmul_gpu returned ");
    __hexa_sl_10 = hexa_str(" (cuBLAS path errored)");
    __hexa_sl_11 = hexa_str("PASS  F-RFC040-GPU-EQUIV-SMALL  cuBLAS Dgemm == CPU oracle == [[4,5],[10,11]] (max|Δ|=");
    __hexa_sl_12 = hexa_str(" < 1e-9)");
    __hexa_sl_13 = hexa_str("FAIL  F-RFC040-GPU-EQUIV-SMALL  max|Δ|=");
    __hexa_sl_14 = hexa_str(" exact_err=");
    __hexa_sl_15 = hexa_str("FAIL  F-RFC040-GPU-EQUIV-RAND  farr_matmul_gpu returned ");
    __hexa_sl_16 = hexa_str("PASS  F-RFC040-GPU-EQUIV-RAND  cuBLAS == CPU on 64x96@96x48 LCG-random (max|Δ|=");
    __hexa_sl_17 = hexa_str(" < TOL_MATMUL 1e-9)");
    __hexa_sl_18 = hexa_str("FAIL  F-RFC040-GPU-EQUIV-RAND  max|Δ|=");
    __hexa_sl_19 = hexa_str(" >= TOL 1e-9 (cuBLAS reduction-order drift exceeds Dgemm fp64 bound)");
    __hexa_sl_20 = hexa_str("FAIL  F-RFC040-GPU-DETERMINISM  one of D1/D2/D3 < 0");
    __hexa_sl_21 = hexa_str("PASS  F-RFC040-GPU-DETERMINISM  3x cuBLAS Dgemm byte-identical (Δ_12=0.0 Δ_23=0.0)");
    __hexa_sl_22 = hexa_str("FAIL  F-RFC040-GPU-DETERMINISM  Δ_12=");
    __hexa_sl_23 = hexa_str(" Δ_23=");
    __hexa_sl_24 = hexa_str("");
    __hexa_sl_25 = hexa_str("=== RFC040 GPU smoke: ");
    __hexa_sl_26 = hexa_str("/");
    __hexa_sl_27 = hexa_str(" PASS ===");
    __hexa_sl_28 = hexa_str("PASS — anima RFC 040 Phase D real-cuBLAS LANDED (HEXA_CUDA build, real GPU, cuBLAS==CPU within 1e-9)");
    __hexa_sl_29 = hexa_str("FAIL — RFC 040 Phase D real-GPU smoke incomplete");
}

HexaVal abs_d(HexaVal x) {
    __hexa_fn_arena_enter();
    if (hexa_truthy(hexa_cmp_lt(x, hexa_float(0.0)))) {
        return __hexa_fn_arena_return(hexa_sub(hexa_float(0.0), x));
    }
    return __hexa_fn_arena_return(x);
    return __hexa_fn_arena_return(hexa_void());
}


HexaVal max_abs_diff(HexaVal c1, HexaVal c2, HexaVal n) {
    __hexa_fn_arena_enter();
    HexaVal m = hexa_float(0.0);
    HexaVal i = hexa_int(0);
    while (HX_BOOL(hexa_cmp_lt(i, n))) {
        HexaVal d = abs_d(hexa_sub(hexa_farr_get(c1, i), hexa_farr_get(c2, i)));
        if (hexa_truthy(hexa_cmp_gt(d, m))) {
            m = d;
        }
        i = hexa_add(i, hexa_int(1));
    }
    return __hexa_fn_arena_return(m);
    return __hexa_fn_arena_return(hexa_void());
}


HexaVal lcg_fill(HexaVal h, HexaVal n, HexaVal seed0) {
    __hexa_fn_arena_enter();
    HexaVal state = seed0;
    HexaVal i = hexa_int(0);
    while (HX_BOOL(hexa_cmp_lt(i, n))) {
        state = hexa_mod(hexa_add(hexa_mul(state, hexa_int(1664525)), hexa_int(1013904223)), hexa_int(2147483647));
        HexaVal u = hexa_sub(hexa_mul(hexa_div(hexa_float(__hx_to_double(state)), hexa_float(2147483647.0)), hexa_float(2.0)), hexa_float(1.0));
        HexaVal _s = hexa_farr_set(h, i, u);
        i = hexa_add(i, hexa_int(1));
    }
    return __hexa_fn_arena_return(hexa_void());
}


HexaVal u_main(void) {
    __hexa_fn_arena_enter();
    HexaVal pass = hexa_int(0);
    HexaVal total = hexa_int(5);
    HexaVal TOL = hexa_float(0.000000001);
    HexaVal avail = hexa_call0(cuda_available);
    HexaVal count = hexa_call0(cuda_device_count);
    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(avail, hexa_int(1))) && hexa_truthy(hexa_cmp_ge(count, hexa_int(1)))))) {
        hexa_println(hexa_add(hexa_add(__hexa_sl_0, hexa_to_string(count)), __hexa_sl_1));
        pass = hexa_add(pass, hexa_int(1));
    } else {
        hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(__hexa_sl_2, hexa_to_string(avail)), __hexa_sl_3), hexa_to_string(count)), __hexa_sl_4));
    }
    HexaVal W = hexa_farr_zeros(hexa_int(8));
    HexaVal wi = hexa_int(0);
    while (HX_BOOL(hexa_cmp_lt(wi, hexa_int(8)))) {
        HexaVal _w = hexa_farr_set(W, wi, hexa_add(hexa_float(__hx_to_double(wi)), hexa_float(0.5)));
        wi = hexa_add(wi, hexa_int(1));
    }
    HexaVal to_dev = hexa_call1(farr_to_device, W);
    HexaVal to_hst = hexa_call1(farr_to_host, W);
    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(to_dev, hexa_int(1))) && hexa_truthy(hexa_eq(to_hst, hexa_int(1))))) && hexa_truthy(hexa_cmp_lt(abs_d(hexa_sub(hexa_farr_get(W, hexa_int(3)), hexa_float(3.5))), TOL))))) {
        hexa_println(__hexa_sl_5);
        pass = hexa_add(pass, hexa_int(1));
    } else {
        hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(__hexa_sl_6, hexa_to_string(to_dev)), __hexa_sl_7), hexa_to_string(to_hst)), __hexa_sl_8), hexa_to_string(hexa_farr_get(W, hexa_int(3)))));
    }
    HexaVal _fw = hexa_farr_free(W);
    HexaVal A = hexa_farr_zeros(hexa_int(6));
    HexaVal _a0 = hexa_farr_set(A, hexa_int(0), hexa_float(1.0));
    HexaVal _a1 = hexa_farr_set(A, hexa_int(1), hexa_float(2.0));
    HexaVal _a2 = hexa_farr_set(A, hexa_int(2), hexa_float(3.0));
    HexaVal _a3 = hexa_farr_set(A, hexa_int(3), hexa_float(4.0));
    HexaVal _a4 = hexa_farr_set(A, hexa_int(4), hexa_float(5.0));
    HexaVal _a5 = hexa_farr_set(A, hexa_int(5), hexa_float(6.0));
    HexaVal B = hexa_farr_zeros(hexa_int(6));
    HexaVal _b0 = hexa_farr_set(B, hexa_int(0), hexa_float(1.0));
    HexaVal _b1 = hexa_farr_set(B, hexa_int(1), hexa_float(0.0));
    HexaVal _b2 = hexa_farr_set(B, hexa_int(2), hexa_float(0.0));
    HexaVal _b3 = hexa_farr_set(B, hexa_int(3), hexa_float(1.0));
    HexaVal _b4 = hexa_farr_set(B, hexa_int(4), hexa_float(1.0));
    HexaVal _b5 = hexa_farr_set(B, hexa_int(5), hexa_float(1.0));
    HexaVal C_cpu = hexa_farr_matmul(A, hexa_int(2), hexa_int(3), B, hexa_int(2));
    HexaVal C_gpu = farr_matmul_gpu(A, hexa_int(2), hexa_int(3), B, hexa_int(2));
    if (hexa_truthy(hexa_cmp_lt(C_gpu, hexa_int(0)))) {
        hexa_println(hexa_add(hexa_add(__hexa_sl_9, hexa_to_string(C_gpu)), __hexa_sl_10));
    } else {
        HexaVal sd = max_abs_diff(C_cpu, C_gpu, hexa_int(4));
        HexaVal exact = hexa_add(hexa_add(hexa_add(abs_d(hexa_sub(hexa_farr_get(C_gpu, hexa_int(0)), hexa_float(4.0))), abs_d(hexa_sub(hexa_farr_get(C_gpu, hexa_int(1)), hexa_float(5.0)))), abs_d(hexa_sub(hexa_farr_get(C_gpu, hexa_int(2)), hexa_float(10.0)))), abs_d(hexa_sub(hexa_farr_get(C_gpu, hexa_int(3)), hexa_float(11.0))));
        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_cmp_lt(sd, TOL)) && hexa_truthy(hexa_cmp_lt(exact, TOL))))) {
            hexa_println(hexa_add(hexa_add(__hexa_sl_11, hexa_to_string(sd)), __hexa_sl_12));
            pass = hexa_add(pass, hexa_int(1));
        } else {
            hexa_println(hexa_add(hexa_add(hexa_add(__hexa_sl_13, hexa_to_string(sd)), __hexa_sl_14), hexa_to_string(exact)));
        }
    }
    HexaVal M = hexa_int(64);
    HexaVal K = hexa_int(96);
    HexaVal N = hexa_int(48);
    HexaVal RA = hexa_farr_zeros(hexa_int(HX_INT(M) * HX_INT(K)));
    HexaVal RB = hexa_farr_zeros(hexa_int(HX_INT(K) * HX_INT(N)));
    lcg_fill(RA, hexa_int(HX_INT(M) * HX_INT(K)), hexa_int(12345));
    lcg_fill(RB, hexa_int(HX_INT(K) * HX_INT(N)), hexa_int(67890));
    HexaVal RC_cpu = hexa_farr_matmul(RA, M, K, RB, N);
    HexaVal RC_gpu = farr_matmul_gpu(RA, M, K, RB, N);
    if (hexa_truthy(hexa_cmp_lt(RC_gpu, hexa_int(0)))) {
        hexa_println(hexa_add(__hexa_sl_15, hexa_to_string(RC_gpu)));
    } else {
        HexaVal rd = max_abs_diff(RC_cpu, RC_gpu, hexa_int(HX_INT(M) * HX_INT(N)));
        if (hexa_truthy(hexa_cmp_lt(rd, TOL))) {
            hexa_println(hexa_add(hexa_add(__hexa_sl_16, hexa_to_string(rd)), __hexa_sl_17));
            pass = hexa_add(pass, hexa_int(1));
        } else {
            hexa_println(hexa_add(hexa_add(__hexa_sl_18, hexa_to_string(rd)), __hexa_sl_19));
        }
    }
    HexaVal D1 = farr_matmul_gpu(RA, M, K, RB, N);
    HexaVal D2 = farr_matmul_gpu(RA, M, K, RB, N);
    HexaVal D3 = farr_matmul_gpu(RA, M, K, RB, N);
    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(hexa_truthy(hexa_cmp_lt(D1, hexa_int(0))) || hexa_truthy(hexa_cmp_lt(D2, hexa_int(0))))) || hexa_truthy(hexa_cmp_lt(D3, hexa_int(0)))))) {
        hexa_println(__hexa_sl_20);
    } else {
        HexaVal g12 = max_abs_diff(D1, D2, hexa_int(HX_INT(M) * HX_INT(N)));
        HexaVal g23 = max_abs_diff(D2, D3, hexa_int(HX_INT(M) * HX_INT(N)));
        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(g12, hexa_float(0.0))) && hexa_truthy(hexa_eq(g23, hexa_float(0.0)))))) {
            hexa_println(__hexa_sl_21);
            pass = hexa_add(pass, hexa_int(1));
        } else {
            hexa_println(hexa_add(hexa_add(hexa_add(__hexa_sl_22, hexa_to_string(g12)), __hexa_sl_23), hexa_to_string(g23)));
        }
    }
    hexa_println(__hexa_sl_24);
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(__hexa_sl_25, hexa_to_string(pass)), __hexa_sl_26), hexa_to_string(total)), __hexa_sl_27));
    if (hexa_truthy(hexa_eq(pass, total))) {
        hexa_println(__hexa_sl_28);
    } else {
        hexa_println(__hexa_sl_29);
    }
    return __hexa_fn_arena_return(hexa_void());
}


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    __hexa_strlit_init();
    u_main();
    fflush(stdout); fflush(stderr);
    return 0;
}
