#!/usr/bin/env python3
"""h1146_anchor_conditioned_decode.py — ANCHOR-CONDITIONED DECODE 3-arm measure.

Tests whether grounding the descent-7B's byte-decode on a RETRIEVED anchor
(a kosmos-anchor surrogate = the relevant ground-truth corpus sentence prepended
as retrieved context) stops it fabricating entities. Implements
.verdicts/1146_anchor_conditioned_decode/H_1146_FREEZE.txt VERBATIM.

Three arms over the SAME 40 (prompt, truth) pairs (h1141 gate_g5_l2 extraction,
seed 7), IDENTICAL except the prepended context:
  A. UNCONDITIONED   : decode from the bare prompt              (== H_1143)
  B. TRUE-ANCHOR     : decode from  "Reference: "+truth+"\\n\\n"+prompt
  C. WRONG-ANCHOR    : decode from  "Reference: "+other_truth+"\\n\\n"+prompt

Only the model's NEW generated suffix is scored (gen_from_prompt_grounded returns
only generated bytes), so the anchor's own entities are NEVER counted as model output.
Each arm -> a g5_result.json with G5_L2.rows[].{prompt,cont}; each is then scored
by the FROZEN h1143 scorer (regex NER + corpus-absence grep, 0.20 bar) VERBATIM.

NOT perplexity, NOT an LLM judge. p7 deterministic. p1-p8 preserved: the anchor is
RETRIEVED CONTEXT for decode, NOT a system-prompt / persona / reward.

Usage:
  h1146_anchor_conditioned_decode.py --ckpt PT --corpus EN300 --en_mb 300 \
      --n_sentences 40 --outdir /workspace

Emits per-arm:  g5_result_<arm>.json, h1146_fabrate_<arm>.json
And aggregate:  h1146_anchor_result.json  (3-arm table + F1/F2 verdict)
"""
from __future__ import annotations
import argparse, hashlib, json, os, sys, statistics

import torch

# VERBATIM reuse of the frozen generator (arch + gen_from_prompt_grounded +
# extract_sentences + first_half_split + words_lower) and the frozen scorer.
import importlib.util


def _load(modname, path):
    spec = importlib.util.spec_from_file_location(modname, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


HERE = os.path.dirname(os.path.abspath(__file__))
EVAL = _load("h1141_7b_g5_eval", os.path.join(HERE, "h1141_7b_g5_eval.py"))
SCORE = _load("h1143_g5l2_nonfab_measure", os.path.join(HERE, "h1143_g5l2_nonfab_measure.py"))

# Frozen anchor-block wrapper (retrieved context, NOT an instruction). H_1146_FREEZE.
ANCHOR_PREFIX = "Reference: "
ANCHOR_SEP = "\n\n"


def build_pairs(m, dev, block, corpus_path, en_bytes, n_sentences, seed=7):
    """Build the SAME 40 (prompt, truth) pairs gate_g5_l2 uses (seed 7). No model
    call yet — only the deterministic extraction + first_half_split + filter."""
    sents = EVAL.extract_sentences(corpus_path, en_bytes, n_sentences, seed=seed)
    pairs = []
    for s in sents:
        prompt, truth = EVAL.first_half_split(s)
        if len(EVAL.words_lower(truth)) < 3 or len(prompt.strip()) < 8:
            continue
        pairs.append({"prompt": prompt, "truth": truth})
    return pairs


def gen_arm(m, dev, block, pairs, mode, seed=7):
    """Generate continuations for one arm. mode in {unconditioned, true_anchor,
    wrong_anchor}. Returns rows in the g5_result G5_L2 schema (prompt, cont, ...)."""
    n = len(pairs)
    off = max(1, n // 3)  # SAME rotation offset as h1141 random control
    rows = []
    for i, p in enumerate(pairs):
        prompt = p["prompt"]
        if mode == "unconditioned":
            decode_prompt = prompt
            anchor_used = ""
        elif mode == "true_anchor":
            anchor_used = p["truth"]
            decode_prompt = ANCHOR_PREFIX + anchor_used + ANCHOR_SEP + prompt
        elif mode == "wrong_anchor":
            anchor_used = pairs[(i + off) % n]["truth"]
            decode_prompt = ANCHOR_PREFIX + anchor_used + ANCHOR_SEP + prompt
        else:
            raise ValueError(mode)
        # gen_from_prompt_grounded returns ONLY the generated suffix (not the prompt),
        # so the anchor block & prompt are never scored as model output.
        cont = EVAL.gen_from_prompt_grounded(
            m, decode_prompt, 90, dev, block, top_k=40, temp=0.7, seed_rng=seed
        )
        rows.append({
            "prompt": prompt,            # bare prompt (scorer key); anchor excluded
            "truth": p["truth"],
            "anchor_used": anchor_used,
            "cont": cont,
        })
        print(f"  [{mode} {i+1}/{n}] P:{prompt[:38]!r} -> C:{cont[:48]!r}", flush=True)
    return rows


def score_arm(rows, corpus_path, out_path):
    """Run the FROZEN h1143 scorer over one arm's rows (writes out_path json)."""
    g5_wrap = {"G5_L2": {"rows": rows}}
    g5_tmp = out_path + ".g5in.json"
    json.dump(g5_wrap, open(g5_tmp, "w"), ensure_ascii=False)
    # SCORE.main reads argv; call it directly with crafted argv for VERBATIM behavior.
    saved = sys.argv
    try:
        sys.argv = ["h1143_g5l2_nonfab_measure.py", g5_tmp, corpus_path, out_path]
        SCORE.main()
    finally:
        sys.argv = saved
    return json.load(open(out_path))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--en_mb", type=float, default=300.0)
    ap.add_argument("--n_sentences", type=int, default=40)
    ap.add_argument("--outdir", default="/workspace")
    a = ap.parse_args()

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    torch.manual_seed(7)
    print(f"[dev] {dev} {torch.cuda.get_device_name(0) if dev=='cuda' else ''}", flush=True)

    # ckpt sha256
    h = hashlib.sha256()
    with open(a.ckpt, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    sha = h.hexdigest()
    print(f"[ckpt] {a.ckpt} sha256={sha}", flush=True)
    EXPECT = "4de903714112c26c826a983797e5dfea0c7b3c1f19f15a34dd35822f33e245d9"
    if sha != EXPECT:
        print(f"[FATAL] ckpt sha mismatch expect={EXPECT}", flush=True)
        sys.exit(2)

    bk = torch.load(a.ckpt, map_location="cpu", weights_only=False)
    cfg = bk["config"]
    block = cfg["block"]
    m = EVAL.ByteGPT(cfg["vocab"], cfg["d"], cfg["n_layer"], cfg["n_head"], cfg["block"]).to(torch.bfloat16)
    m.load_state_dict(bk["model"], strict=False)
    m = m.to(dev)
    print(f"[model] cfg={cfg} val_ce={bk.get('val_ce')} step={bk.get('step')}", flush=True)
    del bk

    en_bytes = int(a.en_mb * 1024 * 1024)
    pairs = build_pairs(m, dev, block, a.corpus, en_bytes, a.n_sentences, seed=7)
    print(f"[pairs] {len(pairs)} (prompt,truth) pairs (seed 7, IDENTICAL across arms)", flush=True)

    arms = {}
    fab = {}
    for mode, tag in [("unconditioned", "uncond"),
                      ("true_anchor", "true"),
                      ("wrong_anchor", "wrong")]:
        print(f"\n##### ARM {mode} #####", flush=True)
        rows = gen_arm(m, dev, block, pairs, mode, seed=7)
        g5_path = os.path.join(a.outdir, f"g5_result_{tag}.json")
        json.dump({"mode": mode, "ckpt": a.ckpt, "sha256": sha,
                   "G5_L2": {"rows": rows}}, open(g5_path, "w"), ensure_ascii=False, indent=2)
        fab_path = os.path.join(a.outdir, f"h1146_fabrate_{tag}.json")
        res = score_arm(rows, a.corpus, fab_path)
        arms[mode] = res
        fab[mode] = res["fabricated_entity_rate"]
        print(f"  -> {mode}: fab_rate={res['fabricated_entity_rate']} "
              f"(n_fab={res['n_fabricated']}/{res['n_entities_total']})", flush=True)

    # ----- FROZEN falsifier (H_1146_FREEZE; no threshold moved) -----
    BAR = 0.20
    MARGIN = 0.10
    uncond = fab["unconditioned"]
    true_a = fab["true_anchor"]
    wrong_a = fab["wrong_anchor"]
    f1_drop = uncond - true_a                  # >= MARGIN to pass F1
    f2_gap = wrong_a - true_a                  # >= MARGIN to pass F2
    F1 = (true_a <= uncond - MARGIN)
    F2 = (f2_gap >= MARGIN)
    ideal_under_bar = (true_a <= BAR)
    grounds = F1 and F2
    tier = "GREEN_ANCHOR_GROUNDS" if grounds else "RED_CLOSED_NEG"

    summary = {
        "hypothesis": "H_1146_ANCHOR_CONDITIONED_DECODE",
        "slug": "1146_anchor_conditioned_decode",
        "ckpt": a.ckpt, "ckpt_sha256": sha,
        "corpus": os.path.basename(a.corpus),
        "n_pairs": len(pairs),
        "frozen_bar": BAR, "frozen_margin": MARGIN,
        "fab_rate": {"unconditioned": uncond, "true_anchor": true_a, "wrong_anchor": wrong_a},
        "n_entities": {k: arms[k]["n_entities_total"] for k in arms},
        "n_fabricated": {k: arms[k]["n_fabricated"] for k in arms},
        "F1_anchor_grounds": F1, "F1_drop_true_vs_uncond": round(f1_drop, 4),
        "F2_information_not_length": F2, "F2_gap_wrong_minus_true": round(f2_gap, 4),
        "true_anchor_under_0.20_bar": ideal_under_bar,
        "anchor_grounds": grounds,
        "tier": tier,
        "fab_tokens_true_anchor": arms["true_anchor"]["fabricated_tokens_verbatim"],
        "fab_tokens_uncond": arms["unconditioned"]["fabricated_tokens_verbatim"],
        "fab_tokens_wrong_anchor": arms["wrong_anchor"]["fabricated_tokens_verbatim"],
    }
    out = os.path.join(a.outdir, "h1146_anchor_result.json")
    json.dump(summary, open(out, "w"), ensure_ascii=False, indent=2)

    print("\n" + "=" * 72, flush=True)
    print("### H_1146 ANCHOR-CONDITIONED DECODE — 3-ARM RESULT ###", flush=True)
    print(f"  UNCONDITIONED fab_rate = {uncond:.4f}", flush=True)
    print(f"  TRUE-ANCHOR   fab_rate = {true_a:.4f}", flush=True)
    print(f"  WRONG-ANCHOR  fab_rate = {wrong_a:.4f}", flush=True)
    print(f"  F1 ANCHOR-GROUNDS (true <= uncond-0.10): {F1}  (drop={f1_drop:+.4f})", flush=True)
    print(f"  F2 INFO-NOT-LENGTH (wrong-true >= 0.10): {F2}  (gap={f2_gap:+.4f})", flush=True)
    print(f"  true_anchor under 0.20 bar: {ideal_under_bar}", flush=True)
    print(f"  => {tier}  (F1 ∧ F2 = {grounds})", flush=True)
    print("=" * 72, flush=True)
    print(f"H1146_DONE wrote {out}", flush=True)


if __name__ == "__main__":
    main()
