#!/usr/bin/env python3
"""Extract the EXACT host-scalar decode functions (verbatim source text) from
core/decode.hexa into a self-contained module so the real hexa compiler+runtime
can exercise the BGB host path (bytegpt_decode_argmax → bg_load → bg_forward_last_W
→ _bg_apply_bind), which never touches the forge_dispatch_*/farr_attn_dt_* device
builtins that the fleet hexa (v0.511/v0.513) lacks. NOT a re-typed mirror — every
function body is copied byte-for-byte from decode.hexa, so a byte-parity PASS here
is a faithful test of the real decode.hexa host source lines.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SRC = os.path.join(REPO, "core", "decode.hexa")

# host-only functions needed to run bytegpt_decode_argmax on base + BGB .bin
WANT = [
    "_bg_rd_u32", "_bg_gelu", "_bg_erf", "_bg_layernorm", "_bg_linear",
    "_bg_transpose", "_bg_mha", "_bg_mha_mm", "_bg_linear_mm",
    "_bg_read_bind_trailer", "_bg_apply_bind",
    "bg_load", "bg_forward_last_W",
    "_bg_kv_new", "_bg_kv_free", "_bg_kv_step", "bg_argmax",
    "bytegpt_decode_argmax",
]

src = open(SRC).read().splitlines(keepends=True)

# index function start lines: match `fn NAME(` or `pub fn NAME(`
starts = {}
for i, ln in enumerate(src):
    m = re.match(r'^(?:pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(', ln)
    if m:
        starts[m.group(1)] = i

def extract(name):
    if name not in starts:
        sys.exit("MISSING function in decode.hexa: " + name)
    i = starts[name]
    # walk to the matching top-level closing brace (first line that is exactly "}")
    depth = 0
    started = False
    out = []
    j = i
    while j < len(src):
        line = src[j]
        out.append(line)
        depth += line.count("{") - line.count("}")
        if "{" in line:
            started = True
        if started and depth <= 0:
            break
        j += 1
    return "".join(out)

blocks = []
for name in WANT:
    blocks.append(extract(name))

# bytegpt_decode_argmax calls _bg_kv_step (host) — good. It references nothing device.
header = (
    "// AUTO-EXTRACTED host-scalar subset of core/decode.hexa (verbatim) for BGB\n"
    "// byte-parity testing on fleet hexa lacking forge_dispatch_*/farr_attn_dt_*\n"
    "// device builtins. Every fn below is copied byte-for-byte from decode.hexa.\n"
    "// Generated by extract_host.py — do NOT hand-edit.\n\n"
)

driver = '''
fn _seed_ids() -> list {
    let s = "hello world "
    let ids = []
    let mut i = 0
    let n = byte_len(s)
    while i < n { ids.push(ord(substring(s, i, i + 1))); i = i + 1 }
    return ids
}

fn _run(tag: string, path: string, gen: int) {
    let r = bytegpt_decode_argmax(path, _seed_ids(), gen)
    let ids = r["ids"]
    let mut line = tag + ":"
    let mut i = 0
    while i < len(ids) { line = line + " " + to_string(to_int(ids[i])); i = i + 1 }
    println(line)
}

fn main() {
    let base = "."
    _run("base", base + "/base.bin", 48)
    _run("I1",   base + "/inj_I1.bin", 48)
    _run("I2",   base + "/inj_I2.bin", 48)
    _run("gate0", base + "/inj_gate0.bin", 48)
}
'''

out_path = os.path.join(HERE, "bgb_host_extract.hexa")
with open(out_path, "w") as f:
    f.write(header)
    f.write("".join(blocks))
    f.write(driver)
print("wrote", out_path, "(%d functions, %d bytes)" % (len(WANT), os.path.getsize(out_path)))
