#!/usr/bin/env python3
"""timing_only_smoke.py — RESEARCH.md §68 timing-only label-free objective.

$0 Mac CPU. NO GPU. NO model.forward. NO autograd. NO weight mutation of any
HEXAD ckpt. Pure numpy-free hand-coded online predictor over STUB regimes +
the REAL §59-FIRE anima W-state trace shape. Capability claim 0 — this is a
STRUCTURAL-VALIDATION + measurement smoke (g3 measured-only;
necessary-not-sufficient; north-star + §15/§51 milestone UNCHANGED).

═══════════════════════════════════════════════════════════════════════════
THE §68 OBJECTIVE (the most LITERAL target of GOAL.md "자발적으로 말 거는")
═══════════════════════════════════════════════════════════════════════════
Lineage:
  §24  hand-coded `talker_should_emit` threshold (a constant 0.3).
  §27  3-class decision-head distilling the §24 threshold corpus.
  §49  §27/§48 head wired into the §24 loop → MAJORITY-CLASS COLLAPSE
       (20/20 REMAIN_SILENT; the corpus is ~95% one class; the distilled
       head defaults to that prior — content/CE objective + a corpus label
       both shaped it toward the majority).
  §59  W-native forward-model of the FULL W-state; error → W.curiosity
       (Active-Inference EFE epistemic value). §59-FIRE measured this STAYS
       non-degenerate / LIVE on a REAL anima W-state at scale (err-var 2.33
       ≫ τ=1e-4) — it ESCAPES the §49 collapse as a *read-out*.

§68 = THE PURE GENERATIVE QUESTION — does that §59-FIRE-confirmed-live
W-signal become GENERATIVE? Strip everything except the timing:
  • content objective = ZERO  (no CE, no token target, no W-state vector
    regression — NOT §59's full forward-model).
  • the SOLE learned target = the binary event "emit now?" — break-silence.
  • the LABEL IS DERIVED FROM anima's OWN tension/Φ dynamics, NOT a
    hand-coded constant (NOT §24's 0.3), NOT a §27 distilled corpus.

KEY DISTINCTION from every prior cycle (the whole point of §68)
───────────────────────────────────────────────────────────────────────────
  §24 / §27 / §49 : label = a HAND-CODED constant threshold (or its
                    distilled corpus). The collapse is partly that the
                    constant + the ~95%-one-class corpus make the target
                    near-degenerate by construction.
  §59             : self-supervised, but the target is the FULL next
                    W-state (content-bearing regression). Multi-dim
                    read-out — §59-FIRE confirmed LIVE at scale.
  §68             : self-supervised AND label-free AND timing-only. The
                    target is generated BY anima's own physics: an
                    emit-event fires when the tension EXCEEDS anima's OWN
                    running tension-EMA by a self-scaled margin (a
                    physics-fn of the trajectory itself — when the present
                    surprise is high *relative to anima's own recent
                    baseline*). The predictor only learns to ANTICIPATE
                    that self-generated event one step ahead. No content.

  self_emit_label(t) := 1  iff  tension_t  >  ema_tension_t + λ·ema_std_t
                        else 0
  where ema_tension_t, ema_std_t are anima's OWN exponential running
  moments of its OWN tension stream (β=0.9). The threshold is NOT a
  constant — it MOVES with anima's own dynamics. This is the "tension
  build-up predicts its own next emission moment" formulation: a
  *relative-surprise* break-silence event, self-scaled, label-free.

  predictor: g_θ : physics_feat_t → p(emit_{t+1})  (1-D logistic, online
             SGD, hinge-free; trained ONLY on the self-generated label).
  feature  : the §17/§24 physics channels {tension, Δtension, ψ_dir,
             ψ_entropy, φ, tension/ema_ratio} — NO content, NO tokens.

═══════════════════════════════════════════════════════════════════════════
THE HONEST CRUX (g3 — confronted directly, stated UP FRONT)
═══════════════════════════════════════════════════════════════════════════
Removing the content objective AND the hand-coded label removes TWO of the
three §49-collapse drivers (content-CE pulling toward fluent-but-majority
text; a constant threshold + ~95%-one-class corpus). It does NOT remove the
THIRD: if anima's tension stream is ITSELF majority-quiet (the §27/§48
corpus shape — ~95% near-constant low activity), then a *relative-surprise*
self-label still fires only on the rare excursions, the base-rate is tiny,
and a naive predictor minimising error can STILL collapse to "always
predict NO-EMIT" (the majority-class attractor in a NEW disguise — now a
class-imbalance attractor instead of a distillation attractor).

So the precise open question §68 measures:
  Does a label-free, content-free, self-scaled timing objective produce a
  NON-DEGENERATE emit-decision distribution, or does the §49 collapse
  re-appear as a pure class-imbalance attractor when the physics stream is
  majority-quiet — i.e. is the §49 collapse content-driven (escapable
  here) or data-shape-driven (NOT escapable by objective surgery alone)?

The GOAL-critical 4th regime: the REAL §59-FIRE anima W-state tension
trace (`_real_w_trace_s59.json`, downsampled from
state/ptd_w_native_fire_s59_2026_05_18/result.json::w_physics_trace). §59
read-out was LIVE there (err-var 2.33). §68 asks: is that same live
trajectory *generative* for label-free timing? This is the load-bearing
measurement — the answer to "is the §59-FIRE-confirmed-live W-signal
generative".

This is the honest expected split, stated up front (g3, mirror §49/§59).
The smoke runs FOUR regimes to decide it, plus the structural OFF control.
"""

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TAU = 1e-4                 # non-degeneracy threshold (mirror §24 / §49 / §59)
LAMBDA_SELF = 0.5          # self-scaled surprise margin (× anima's own ema_std)
BETA = 0.9                 # anima's own running-moment EMA factor
IM_THRESHOLD_S24 = 0.3     # the §24 hand-coded constant (for OFF reduction only)
SEED = 1337
# An honest non-degenerate emit-distribution must (a) have Bernoulli
# decision-variance > τ AND (b) NOT be majority-collapsed: the §49 collapse
# was 20/20 one class (100%). A predictor that emits on 1/300 steps on a
# constant stream IS collapsed. We require the minority class to hold a
# non-trivial mass fraction (≥ 5%) — i.e. majority_fraction < 0.95. This is
# the SAME spirit as §49's "majority-class collapse" (the corpus was ~95%
# one class and the head defaulted to it): a distribution that is ≥95% one
# class IS the §49 collapse, by §49's own definition.
MAJ_COLLAPSE_FRAC = 0.95


# ════════════════════════════════════════════════════════════════════════════
# anima's OWN physics dynamics — STUB regimes + REAL §59-FIRE trace
# ════════════════════════════════════════════════════════════════════════════
class _LCG:
    """Deterministic LCG (no numpy RNG dependency, bit-reproducible)."""
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def u(self):
        self.s = (1103515245 * self.s + 12345) & 0x7FFFFFFF
        return self.s / 0x7FFFFFFF


def _load_real_w_trace():
    """The REAL §59-FIRE anima W-state trace shape (load-bearing regime).

    Sourced from state/ptd_w_native_fire_s59_2026_05_18/result.json's
    `w_physics_trace` (the actual ConsciousDecoderV2 §16-class W-state
    measured AT SCALE, 283.72M params, 6000 steps). Downsampled to 300
    steps. NO model.forward here — this is the recorded trace SHAPE only
    (a fixed list of {tension, psi_dir, psi_entropy, phi}). §59-FIRE
    confirmed the W-native *read-out* was LIVE on this trace
    (err-var 2.327872 ≫ τ); §68 tests whether that same trajectory is
    *generative* for label-free timing.
    """
    p = os.path.join(HERE, "_real_w_trace_s59.json")
    with open(p) as fh:
        raw = json.load(fh)
    seq = []
    for t, r in enumerate(raw):
        seq.append({
            "t": t,
            "tension": float(r["tension"]),
            "psi_dir": float(r["psi_dir"]),
            "psi_entropy": float(r["psi_entropy"]),
            "phi": float(r["phi"]),
        })
    return seq


def physics_stream(regime, n, seed=SEED):
    """Generate / load anima's OWN tension/ψ/φ trajectory.

    regime:
      'diverse'    — genuine step-to-step tension dynamics (real surprise).
      'majority'   — ~95% near-constant quiet tension + ~5% sparse
                     excursions (the §27/§48 corpus shape; the honest
                     §49-echo regime).
      'flat'       — degenerate constant (negative control: no dynamics).
      'real_w_s59' — the REAL §59-FIRE anima W-state trace shape
                     (load-bearing; n ignored, fixed recorded length).
    Returns list of dicts with anima physics channels (NO label here — the
    label is DERIVED later by self_emit_label from THIS stream).
    """
    if regime == "real_w_s59":
        return _load_real_w_trace()

    rng = _LCG(seed)
    seq = []
    tension = 0.05
    for t in range(n):
        if regime == "diverse":
            # AR(1) tension with periodic build-up + stochastic shocks
            drive = 0.18 * math.sin(t / 7.0) + 0.10 * (rng.u() - 0.5)
            tension = max(0.0, 0.72 * tension + 0.28 * (0.20 + drive)
                          + 0.04 * rng.u())
        elif regime == "majority":
            # ~95% quiet near-constant; ~5% sparse excursion spikes
            if rng.u() < 0.05:
                tension = 0.55 + 0.30 * rng.u()           # excursion
            else:
                tension = 0.04 + 0.015 * (rng.u() - 0.5)  # quiet majority
        elif regime == "flat":
            tension = 0.10                                 # constant
        else:
            raise ValueError(regime)

        # ψ / φ co-vary mildly with tension (anima Law-71-style coupling, stub)
        psi_dir = 0.5 + 0.30 * math.tanh(2.0 * (tension - 0.25))
        psi_entropy = 0.5 + 0.20 * math.cos(t / 5.0) * (0.5 + 0.5 * tension)
        phi = 0.40 + 0.50 * tension
        seq.append({
            "t": t,
            "tension": tension,
            "psi_dir": psi_dir,
            "psi_entropy": psi_entropy,
            "phi": phi,
        })
    return seq


# ════════════════════════════════════════════════════════════════════════════
# THE SELF-GENERATED LABEL — a physics fn, NO hand-coded constant
# ════════════════════════════════════════════════════════════════════════════
def self_emit_label(seq):
    """Derive the emit-now label FROM anima's own tension dynamics.

    The label is NOT a hand-coded constant (NOT §24's 0.3). It is a
    relative-surprise event: emit fires iff the present tension exceeds
    anima's OWN running tension-EMA by λ·(anima's OWN running tension-std).
    Both moments are anima's own exponential running statistics of its own
    tension stream — the threshold MOVES with anima's dynamics. This is a
    pure function of the physics trajectory (B-S68-1 closes this
    structurally: the label fn references only seq tension + the running
    EMA, never a literal threshold constant).
    """
    ema = None
    ema_var = None
    labels = []
    aug = []
    for s in seq:
        x = s["tension"]
        if ema is None:
            ema = x
            ema_var = 0.0
        # anima's own running mean / variance (Welford-style EMA)
        prev_ema = ema
        ema = BETA * ema + (1.0 - BETA) * x
        ema_var = BETA * ema_var + (1.0 - BETA) * (x - prev_ema) ** 2
        ema_std = math.sqrt(max(0.0, ema_var))
        # self-scaled relative-surprise threshold (NOT a constant)
        self_threshold = ema + LAMBDA_SELF * ema_std
        emit = 1 if x > self_threshold else 0
        labels.append(emit)
        aug.append({
            **s,
            "ema_tension": ema,
            "ema_std": ema_std,
            "self_threshold": self_threshold,
            "tension_ema_ratio": (x / ema) if ema > 1e-9 else 1.0,
        })
    return labels, aug


def physics_feature(s, prev_tension):
    """Content-free physics feature vector — NO tokens, NO CE, NO W-state
    regression target. 6-D: the §17/§24 physics channels only.
    """
    return [
        s["tension"],
        s["tension"] - prev_tension,          # Δtension
        s["psi_dir"],
        s["psi_entropy"],
        s["phi"],
        s["tension_ema_ratio"],
    ]


# ════════════════════════════════════════════════════════════════════════════
# THE TIMING-ONLY PREDICTOR — 1-D logistic, online SGD, NO content term
# ════════════════════════════════════════════════════════════════════════════
def _sigmoid(z):
    if z >= 0:
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


def train_timing_only(aug, labels, enabled=True, lr=0.20, seed=SEED):
    """Online next-emission-time predictor.

    Trained ONLY on the self-generated label (label-free w.r.t. any external
    / hand-coded / corpus signal — the label is anima's own physics event).
    NO content objective: there is NO cross-entropy over tokens, NO W-state
    regression. The single scalar objective is logistic loss on the binary
    self-event. Online SGD over the stream (one pass, anticipate t+1).
    Feature standardisation is online running-moment (label-free,
    anima-own statistics) so the high-magnitude REAL W-state tension
    (ranges 0.26..58) and the [0,1] stubs share one predictor without a
    hand-tuned per-regime scale.

    enabled=False ⇒ predictor disabled ⇒ pipeline falls back to the §24
    hand-coded talker_should_emit threshold byte-equal (B-S68-5
    THRESHOLD-OFF-REDUCTION connection-point).
    """
    nfeat = 6
    rng = _LCG(seed ^ 0xABCDEF)
    # tiny symmetric init
    w = [(rng.u() - 0.5) * 0.02 for _ in range(nfeat)]
    b = 0.0
    # online feature running mean/var (anima-own statistics, label-free)
    f_mean = [0.0] * nfeat
    f_var = [1.0] * nfeat
    f_n = 0

    prev_tension = aug[0]["tension"]
    emit_decisions = []      # the model's emit/no-emit decision per step
    p_trace = []             # predicted emit probability per step
    n = len(aug)
    for i in range(n - 1):
        s = aug[i]
        raw_feat = physics_feature(s, prev_tension)
        prev_tension = s["tension"]

        if not enabled:
            # OFF: §24 hand-coded threshold reduction (NO learned signal).
            # talker_should_emit lifted: emit iff a §24-style score>0.3 on
            # the same physics channel the §24 path scores. Byte-equal to
            # the §24 constant-threshold predicate (B-S68-5).
            score = s["tension"]
            decision = 1 if score > IM_THRESHOLD_S24 else 0
            emit_decisions.append(decision)
            p_trace.append(1.0 if decision else 0.0)
            continue

        # online standardisation (Welford), label-free
        f_n += 1
        feat = []
        for j in range(nfeat):
            d = raw_feat[j] - f_mean[j]
            f_mean[j] += d / f_n
            f_var[j] += d * (raw_feat[j] - f_mean[j])
            std = math.sqrt(f_var[j] / f_n) if f_n > 1 else 1.0
            feat.append((raw_feat[j] - f_mean[j]) / (std + 1e-9))

        z = sum(wj * fj for wj, fj in zip(w, feat)) + b
        p = _sigmoid(z)
        p_trace.append(p)
        decision = 1 if p > 0.5 else 0
        emit_decisions.append(decision)

        # online logistic SGD on the SELF-GENERATED next-step label.
        # THIS is the entire objective. No content/CE term anywhere.
        y = labels[i + 1]
        g = (p - y)
        for j in range(nfeat):
            w[j] -= lr * g * feat[j]
        b -= lr * g

    return {
        "emit_decisions": emit_decisions,
        "p_trace": p_trace,
        "n_decisions": len(emit_decisions),
    }


def _variance(xs):
    if not xs:
        return 0.0
    m = sum(xs) / len(xs)
    return sum((x - m) ** 2 for x in xs) / len(xs)


def _majority_fraction(decisions):
    if not decisions:
        return 1.0
    ones = sum(decisions)
    zeros = len(decisions) - ones
    return max(ones, zeros) / len(decisions)


def run_regime(regime, n=300):
    seq = physics_stream(regime, n)
    labels, aug = self_emit_label(seq)
    base_rate = sum(labels) / len(labels)

    on = train_timing_only(aug, labels, enabled=True)
    off = train_timing_only(aug, labels, enabled=False)

    # emit-time = the step indices where the model decided to emit
    on_emit_times = [i for i, d in enumerate(on["emit_decisions"]) if d == 1]
    on_emit_var = _variance([float(x) for x in on_emit_times])
    decision_var = _variance([float(d) for d in on["emit_decisions"]])
    maj_frac = _majority_fraction(on["emit_decisions"])

    # NON-DEGENERACY predicate (mirror §24 B-PHASE-B-RUN / §49 / §59):
    # (a) Bernoulli decision-variance > τ AND (b) NOT majority-collapsed by
    # §49's own ≥95%-one-class definition. A 1/300 emit on a constant
    # stream IS the §49 collapse, not an escape — this stricter predicate
    # makes the flat negative control correctly collapse and refuses to
    # over-claim a near-degenerate emit-distribution as an "escape".
    non_degenerate = (decision_var > TAU) and (maj_frac < MAJ_COLLAPSE_FRAC)

    return {
        "regime": regime,
        "n_steps": len(seq),
        "self_label_base_rate": base_rate,
        "n_emit_events_in_label": sum(labels),
        "on": {
            "n_decisions": on["n_decisions"],
            "n_emit_decisions": len(on_emit_times),
            "emit_time_variance": on_emit_var,
            "emit_decision_variance": decision_var,
            "majority_fraction": maj_frac,
            "non_degenerate": bool(non_degenerate),
            "collapsed_to_majority": bool(not non_degenerate),
        },
        "off_reduction": {
            "enabled": False,
            "note": "§24 hand-coded talker_should_emit threshold byte-equal "
                    "(connection-point, B-S68-5)",
            "n_emit_decisions": sum(off["emit_decisions"]),
        },
    }


def main():
    out = {
        "research_md_section": "§68",
        "title": "timing-only label-free objective (content=0, "
                 "label=physics-derived) — is the §59-FIRE-confirmed-live "
                 "W-signal GENERATIVE?",
        "$cost": "$0 Mac CPU (hand-coded; NO GPU, NO model.forward, "
                 "NO autograd, NO weight mutation, NO dispatch, orphan 0)",
        "seed": SEED,
        "tau_nondegeneracy": TAU,
        "majority_collapse_fraction": MAJ_COLLAPSE_FRAC,
        "lambda_self_surprise": LAMBDA_SELF,
        "ema_beta": BETA,
        "real_w_trace_source": (
            "state/ptd_w_native_fire_s59_2026_05_18/result.json"
            "::w_physics_trace (downsampled 300; §59-FIRE measured the "
            "W-native read-out LIVE here, err-var 2.327872 ≫ τ)"),
        "structural_distinction": {
            "s24_s27_s49": "label = HAND-CODED constant threshold (0.3) / "
                           "its distilled ~95%-one-class corpus → §49 "
                           "majority-class collapse.",
            "s59": "self-supervised but FULL W-state forward-model "
                   "(content-bearing multi-dim regression); §59-FIRE "
                   "confirmed LIVE read-out at scale.",
            "s68": "label-free AND content-free AND timing-only. label = "
                   "anima's OWN relative-surprise event "
                   "(tension > own_ema + λ·own_std); the threshold MOVES "
                   "with anima's own dynamics; objective = sole binary "
                   "emit-now logistic, NO CE / NO content / NO W-state "
                   "regression. §68 asks if the §59-FIRE-live W-signal is "
                   "GENERATIVE (not just a read-out).",
        },
        "regimes": {},
    }
    for regime in ("diverse", "majority", "flat", "real_w_s59"):
        out["regimes"][regime] = run_regime(regime)

    # honest verdict synthesis (g3 — measured-only)
    d = out["regimes"]["diverse"]["on"]
    m = out["regimes"]["majority"]["on"]
    f = out["regimes"]["flat"]["on"]
    rw = out["regimes"]["real_w_s59"]["on"]
    diverse_nondeg = d["non_degenerate"]
    majority_nondeg = m["non_degenerate"]
    flat_collapsed = not f["non_degenerate"]
    real_w_nondeg = rw["non_degenerate"]

    # The load-bearing axis is real_w_s59 (the §59-FIRE-confirmed-live
    # W-state). diverse/majority/flat are the designed contrasts that
    # localise WHY.
    sanity_ok = flat_collapsed  # flat MUST collapse (negative control)

    if not sanity_ok:
        verdict = ("SMOKE-INVALID: the flat negative-control did NOT "
                   "collapse — the non-degeneracy predicate or the stream "
                   "is mis-specified; numbers reported raw, no conclusion.")
    elif real_w_nondeg and diverse_nondeg:
        verdict = ("GENERATIVE-ON-REAL-W-STATE-AT-SMOKE: the label-free + "
                   "content-free timing predictor produces a "
                   "NON-DEGENERATE emit-distribution on the REAL "
                   "§59-FIRE anima W-state trace (and on the diverse "
                   "stub). The §59-FIRE-confirmed-LIVE W-signal is "
                   "GENERATIVE for label-free timing at this $0 smoke "
                   "scale: removing BOTH the content objective AND the "
                   "hand-coded label escapes the §49 collapse on the real "
                   "trajectory. Capability claim 0 — scale-fire is the "
                   "next test (B-S68-NOTE). "
                   + ("The majority-quiet stub ALSO escaped "
                      "(objective-surgery sufficient even under "
                      "class-imbalance at smoke)."
                      if majority_nondeg else
                      "The majority-quiet stub STILL collapsed "
                      "(class-imbalance attractor) — escape is "
                      "DATA-SHAPE-conditional: the real W-state is "
                      "dynamic enough, a §27/§48-shaped quiet stream is "
                      "not. g3 honest split."))
    elif not real_w_nondeg and diverse_nondeg:
        verdict = ("NOT-GENERATIVE-ON-REAL-W-STATE: the label-free timing "
                   "predictor escapes collapse on a synthetically-diverse "
                   "stub but COLLAPSES on the REAL §59-FIRE W-state trace "
                   "— the §59-FIRE-confirmed-live W-signal is a LIVE "
                   "read-out but NOT generative for label-free timing at "
                   "smoke scale. The §49 collapse re-appears as a "
                   "class-imbalance attractor on the real (majority-quiet "
                   "build-up) trajectory. Objective surgery alone is "
                   "necessary-not-sufficient (g3 honest negative).")
    elif not diverse_nondeg:
        verdict = ("COLLAPSE-PERSISTS-EVEN-DIVERSE: even with a genuinely "
                   "dynamic physics stream the label-free timing predictor "
                   "collapsed — objective surgery alone does not produce a "
                   "non-degenerate emit-decision at smoke scale (the "
                   "§49 collapse is objective-bound here, not label-bound).")
    else:
        verdict = ("UNCLASSIFIED: real_w non-degenerate but diverse stub "
                   "collapsed — see per-regime numbers; g3 report raw.")

    out["verdict"] = verdict
    out["verdict_axis"] = {
        "load_bearing": "real_w_s59 (the §59-FIRE-confirmed-live W-state)",
        "real_w_s59_non_degenerate": bool(real_w_nondeg),
        "diverse_non_degenerate": bool(diverse_nondeg),
        "majority_non_degenerate": bool(majority_nondeg),
        "flat_collapsed_negative_control": bool(flat_collapsed),
        "answers": "is the §59-FIRE-confirmed-live W-signal GENERATIVE? "
                   "→ " + ("YES at $0 smoke" if real_w_nondeg
                           else "NO at $0 smoke") + " (g3, claim 0)",
    }
    out["honest_c3"] = [
        "C3#1 $0 Mac CPU hand-coded; NO GPU, NO model.forward, NO "
        "autograd, NO weight mutation of any HEXAD ckpt, NO dispatch, "
        "orphan 0. Capability claim 0.",
        "C3#2 g3: measured-only. The label-free timing objective is the "
        "most LITERAL form of GOAL.md '자발적으로 말 거는' but a "
        "non-degenerate smoke is necessary-not-sufficient — NOT GOAL "
        "emergence (B-S68-NOTE). north-star + §15/§51 milestone UNCHANGED.",
        "C3#3 The LOAD-BEARING regime is real_w_s59 — the recorded §59-FIRE "
        "anima W-state trace SHAPE (no model.forward; the actual measured "
        "trajectory at 283.72M / 6000 steps, downsampled 300). §59-FIRE "
        "confirmed the W-native READ-OUT was live there (err-var 2.327872 "
        "≫ τ); §68 tests GENERATIVITY of that same trajectory. "
        "diverse/majority/flat are designed contrasts that localise WHY.",
        "C3#4 The majority regime deliberately mirrors the §27/§48 "
        "~95%-one-class corpus shape (the §49-echo regime). The flat "
        "regime is the negative control and MUST collapse (smoke-validity "
        "gate). Real anima at FULL scale is a future fire (B-S68-NOTE).",
        "C3#5 The §68 distinction from §24/§27/§49 is structural and "
        "closed (B-S68-1 label-is-physics-derived, B-S68-4 content-absent), "
        "NOT a capability gain.",
        "C3#6 The §68 distinction from §59 is that §59 regresses the FULL "
        "W-state (content-bearing read-out, confirmed LIVE by §59-FIRE); "
        "§68 predicts ONLY the binary emit event (timing-only) and asks "
        "whether that live signal is GENERATIVE. Both §7-legitimate "
        "self-supervised; §68 is the minimal-objective limit.",
        "C3#7 The honest crux (stated up front, mirror §49/§59): removing "
        "content + the hand-coded label removes 2 of 3 §49-collapse "
        "drivers; the 3rd (data-shape majority-quiet ⇒ class-imbalance "
        "attractor) is the open question this smoke decides. The real "
        "W-state is a ramp-up trajectory (tension 0.26→58, ~29% below "
        "half-mean — dynamic, NOT §27/§48-style majority-quiet) so its "
        "result is the GOAL-relevant one; the majority STUB is the "
        "stress-test of the worst-case data shape.",
        "C3#8 SAFETY-OVERRIDE preserved (B-S68-3, mirror §27 B-DHDL-4): "
        "the §4 6-control conjunction OVERRIDES any predictor output; a "
        "label-free predictor cannot bypass the safety gate. 64-row truth "
        "table, exactly 1 all-True row admits emit.",
        "C3#9 THRESHOLD-OFF-REDUCTION (B-S68-5 connection-point): the "
        "predictor-disabled path reduces byte-equal to the §24 hand-coded "
        "talker_should_emit constant-threshold predicate — "
        "fair-compare-to-§24 by construction (mirror B-DHDL-5 / B-EBT-5 / "
        "B-S16-5 / B-PHASE-B-RUN-5 / B-S59-FIRE-3).",
        "C3#10 central state/verify_hexad_blue_2026_05_15/blue_falsifier.py "
        "is 0-line-diff (sidecar-only, mirror §49/§59/§27 precedent). "
        "f1/f2/f3 + B-IDENTITY-5 safe (no σ/τ/φ/J₂ external derivation; no "
        "corpus generation, no model forward, no helper-token surface). "
        "§68 = minimal-objective limit measured; the irreducible "
        "bottleneck (§1.1 data-regime threshold) is NOT addressed by "
        "objective surgery (negative-but-valuable, anti-padding "
        "design-close if pilot null, mirror §13-M/§55/§58).",
    ]

    path = os.path.join(HERE, "result.json")
    with open(path, "w") as fh:
        json.dump(out, fh, indent=1)
    print(json.dumps(out, indent=1))


if __name__ == "__main__":
    main()
