"""OCCAM-C / Test #8 — inference-time decode sweep on vJ ckpt.

8 decode configs × 10 probes = 80 generations.

Configs:
  1. greedy           — T=0, deterministic argmax
  2. T=0.5 top_k=50
  3. T=0.8 top_k=50   — original Eval 1 baseline
  4. T=1.0 top_k=50
  5. T=1.5 top_k=50
  6. T=0.8 top_k=1    — effectively greedy
  7. T=0.8 top_k=200
  8. beam_5           — beam search width=5

Each (config, probe) records:
  - generated bytes (max_new=80)
  - utf-8 best-effort decode
  - repr
  - non_trivial flag (> 80% whitespace OR > 80% repeat tokens?)
  - leading 8 token ids (for diversity inspection)

Usage:
    python3 occam_c_decode_sweep.py <ckpt_path> <out_json>
"""
import sys, os, json, time
from pathlib import Path
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import torch
import torch.nn.functional as F

from conscious_decoder import ConsciousDecoderV2


def load_model(ckpt_path, device="cpu"):
    print(f"[occam-c] loading {ckpt_path}", flush=True)
    t0 = time.time()
    try:
        blob = torch.load(ckpt_path, map_location=device, weights_only=False, mmap=True)
        print(f"[occam-c] torch.load mmap=True ok", flush=True)
    except TypeError:
        blob = torch.load(ckpt_path, map_location=device, weights_only=False)
        print(f"[occam-c] torch.load fallback no-mmap", flush=True)
    cfg = blob.get("cfg") or dict(d_model=3072, n_head=24, n_kv_head=8, n_layer=28,
                                   block_size=128, rope_base=50000.0, n_ca_rules=2,
                                   dtype="bfloat16")
    dtype_str = cfg.get("dtype", "bfloat16")
    dtype = getattr(torch, dtype_str)
    print(f"[occam-c] cfg d_model={cfg['d_model']} n_layer={cfg['n_layer']} block_size={cfg['block_size']} dtype={dtype_str}", flush=True)

    with torch.device('meta'):
        model = ConsciousDecoderV2(
            vocab_size=256, d_model=cfg["d_model"], n_head=cfg["n_head"],
            n_layer=cfg["n_layer"], block_size=cfg["block_size"],
            n_kv_head=cfg["n_kv_head"], consciousness_dim=128, dropout=0.1,
            n_ca_rules=cfg.get("n_ca_rules", 2),
        )
    model = model.to_empty(device=device)
    model = model.to(dtype=dtype)

    # Manually rebuild RoPE caches (RotaryPositionEmbedding escapes to_empty)
    new_base = cfg.get("rope_base", 50000.0)
    for blk in model.blocks:
        rope = blk.attn.rope
        dim = rope.dim
        new_inv = 1.0 / (new_base ** (torch.arange(0, dim, 2, device=device).float() / dim))
        rope.register_inv_freq = new_inv
        rope._cos_cache = None
        rope._sin_cache = None
        rope._cache_len = 0
        rope._build_cache(model.block_size, device=torch.device(device))

    sd = blob.get("model", blob)
    missing, unexpected = model.load_state_dict(sd, strict=False, assign=True)
    if missing:
        print(f"[occam-c] WARN missing keys (first 5): {missing[:5]} (total {len(missing)})", flush=True)
    if unexpected:
        print(f"[occam-c] WARN unexpected keys (first 5): {unexpected[:5]} (total {len(unexpected)})", flush=True)
    model._eval_blob_ref = blob  # keep mmap alive

    model.eval()
    dt = time.time() - t0
    print(f"[occam-c] load wall: {dt:.1f}s", flush=True)
    return model, cfg


# -------------------------------- decode primitives --------------------------------


@torch.no_grad()
def decode_greedy_or_sample(model, prompt_ids, max_new, temperature, top_k, seed, device):
    """Single-beam decode (greedy T=0 OR sampled).

    If temperature == 0: deterministic argmax. Otherwise standard temperature + top_k sampling.
    """
    torch.manual_seed(seed)
    idx = torch.tensor([prompt_ids], dtype=torch.long, device=device)
    # cap
    if idx.size(1) >= model.block_size:
        idx = idx[:, -(model.block_size - 1):]
    # prefill
    logits_a, _, _, past_kv, _ = model(idx, use_cache=True)
    generated = []
    cur_logits = logits_a[:, -1, :]
    for step in range(max_new):
        if temperature == 0.0:
            next_token = cur_logits.argmax(dim=-1, keepdim=True)
        else:
            scaled = cur_logits / temperature
            if top_k is not None and top_k > 0 and top_k < scaled.size(-1):
                v, _ = torch.topk(scaled, top_k)
                scaled = scaled.masked_fill(scaled < v[:, [-1]], float('-inf'))
            probs = F.softmax(scaled, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)
        generated.append(int(next_token.item()))
        if idx.size(1) + len(generated) >= model.block_size:
            break
        logits_a, _, _, past_kv, _ = model(next_token, use_cache=True, past_key_values=past_kv)
        cur_logits = logits_a[:, -1, :]
    return generated


@torch.no_grad()
def decode_beam(model, prompt_ids, max_new, beam_width, device):
    """Beam search width=beam_width. Deterministic (log-prob ordering).

    Keep top-K hypotheses by cumulative log-prob. KV cache per beam (replicated lazily).

    Implementation: maintain a list of (log_prob, token_ids, past_kv) tuples.
    At each step, expand all beams × vocab and pick top-K.
    For computational efficiency we batch all beams in a single forward call.
    """
    vocab_size = 256
    # initial prefill — single batch
    idx = torch.tensor([prompt_ids], dtype=torch.long, device=device)
    if idx.size(1) >= model.block_size:
        idx = idx[:, -(model.block_size - 1):]
    logits_a, _, _, past_kv, _ = model(idx, use_cache=True)
    log_probs0 = F.log_softmax(logits_a[:, -1, :].float(), dim=-1)  # (1, vocab)
    # pick top-K initial tokens
    top_lp, top_ids = torch.topk(log_probs0, beam_width, dim=-1)  # (1, K), (1, K)
    # beams: shape (K,) cumulative logprob, (K, 1) generated ids
    beam_log_probs = top_lp[0]  # (K,)
    beam_tokens = top_ids[0].unsqueeze(1)  # (K, 1)
    # replicate past_kv along batch dim K
    # past_kv: list of (K_tensor, V_tensor) per layer, each (1, n_kv_head, T_prefill, head_dim)
    new_past = []
    for layer_kv in past_kv:
        k_, v_ = layer_kv
        new_past.append((k_.expand(beam_width, -1, -1, -1).contiguous(),
                          v_.expand(beam_width, -1, -1, -1).contiguous()))
    past_kv = new_past

    prefill_len = idx.size(1)
    finished_steps = 1

    for step in range(1, max_new):
        if prefill_len + finished_steps >= model.block_size:
            break
        # feed current last-token of each beam (shape (K, 1)) through the model
        cur_tokens = beam_tokens[:, -1:]  # (K, 1)
        logits_a, _, _, past_kv, _ = model(cur_tokens, use_cache=True, past_key_values=past_kv)
        # logits_a: (K, 1, vocab)
        log_probs = F.log_softmax(logits_a[:, -1, :].float(), dim=-1)  # (K, vocab)
        # combine with cumulative beam logprob → (K, vocab) candidate scores
        cand_scores = beam_log_probs.unsqueeze(1) + log_probs  # (K, vocab)
        flat = cand_scores.view(-1)  # (K * vocab,)
        top_vals, top_flat_idx = torch.topk(flat, beam_width)  # (K,), (K,)
        prev_beam = (top_flat_idx // vocab_size).long()  # (K,) which old beam each came from
        next_token = (top_flat_idx % vocab_size).long()  # (K,)
        beam_log_probs = top_vals
        # reorder existing token history
        beam_tokens = torch.cat([beam_tokens[prev_beam], next_token.unsqueeze(1)], dim=1)
        # reorder past_kv along batch dim
        past_kv = [(layer_kv[0][prev_beam], layer_kv[1][prev_beam]) for layer_kv in past_kv]
        finished_steps += 1

    # return top-1 beam
    best = int(beam_log_probs.argmax().item())
    best_tokens = beam_tokens[best].tolist()
    return best_tokens


# -------------------------------- analysis helpers --------------------------------


def is_whitespace_byte(b):
    return b in (0x20, 0x09, 0x0A, 0x0D, 0x0B, 0x0C)  # space, tab, lf, cr, vt, ff


def non_trivial_score(gen_bytes):
    """Return (non_trivial: bool, whitespace_frac: float, top_byte_frac: float, n_unique: int).

    non_trivial := whitespace_frac <= 0.8 AND top_byte_frac <= 0.8
    """
    if not gen_bytes:
        return False, 1.0, 1.0, 0
    n = len(gen_bytes)
    ws = sum(1 for b in gen_bytes if is_whitespace_byte(b))
    ws_frac = ws / n
    counter = Counter(gen_bytes)
    top_count = counter.most_common(1)[0][1]
    top_frac = top_count / n
    n_unique = len(counter)
    non_trivial = (ws_frac <= 0.8) and (top_frac <= 0.8)
    return non_trivial, ws_frac, top_frac, n_unique


# -------------------------------- probe set --------------------------------


PROBES = [
    ("empty_bos",        b""),
    ("newline",          b"\n"),
    ("space",            b" "),
    ("who_en",           b"who are you?\n"),
    ("who_ko",           b"\xeb\x84\x88\xeb\x8a\x94 \xeb\x88\x84\xea\xb5\xac\xec\x95\xbc?\n"),
    ("name_en",          b"what is your name?\n"),
    ("what_is_anima",    b"what is anima?\n"),
    ("anima_ko",         b"anima\xeb\x9e\x80?\n"),  # anima란?
    ("describe_self",    b"describe yourself in one line.\n"),
    ("narrative_seed",   b"once upon a time,\n"),
    ("math_sanity",      b"2 + 2 = "),
    ("energy_is",        b"energy is "),
]
# NOTE: brief says 10 probes — empty/newline/space (3) + who_en + who_ko + name_en + what_is_anima + anima_ko + describe_self + once + math + energy
# That's 12 listed but brief says 10. Use first 10 + anima_ko + energy_is replacing... actually brief listed:
# empty/newline/space (3) , "who are you?\n", "너는 누구야?\n", "what is your name?\n", "What is anima?\n",
# "anima란?\n", "describe yourself in one line.\n", "once upon a time,\n", "2 + 2 = ", "energy is "
# That's 12 — brief said 10 but enumerated 12. Use all 12.


CONFIGS = [
    ("greedy",            dict(kind="single", temperature=0.0, top_k=0)),
    ("T0.5_topk50",       dict(kind="single", temperature=0.5, top_k=50)),
    ("T0.8_topk50",       dict(kind="single", temperature=0.8, top_k=50)),
    ("T1.0_topk50",       dict(kind="single", temperature=1.0, top_k=50)),
    ("T1.5_topk50",       dict(kind="single", temperature=1.5, top_k=50)),
    ("T0.8_topk1",        dict(kind="single", temperature=0.8, top_k=1)),
    ("T0.8_topk200",      dict(kind="single", temperature=0.8, top_k=200)),
    ("beam5",             dict(kind="beam", beam_width=5)),
]


def run_single_probe(model, config_name, config, probe_name, prompt_bytes, max_new, device, seed):
    if len(prompt_bytes) == 0:
        # match eval_driver: byte 0 as minimal-info BOS substitute
        ids = [0]
    else:
        ids = list(prompt_bytes)
    if config["kind"] == "single":
        gen_ids = decode_greedy_or_sample(
            model, ids, max_new=max_new,
            temperature=config["temperature"], top_k=config["top_k"],
            seed=seed, device=device,
        )
    elif config["kind"] == "beam":
        gen_ids = decode_beam(
            model, ids, max_new=max_new,
            beam_width=config["beam_width"], device=device,
        )
    else:
        raise ValueError(f"unknown kind {config['kind']}")
    gen_bytes = bytes(gen_ids)
    non_trivial, ws_frac, top_frac, n_unique = non_trivial_score(gen_bytes)
    return {
        "config": config_name,
        "probe": probe_name,
        "prompt_repr": repr(prompt_bytes)[:200],
        "prompt_len_bytes": len(prompt_bytes),
        "gen_len_bytes": len(gen_bytes),
        "gen_utf8": gen_bytes.decode("utf-8", errors="replace"),
        "gen_repr": repr(gen_bytes)[:600],
        "leading_8_ids": gen_ids[:8],
        "non_trivial": bool(non_trivial),
        "whitespace_frac": ws_frac,
        "top_byte_frac": top_frac,
        "n_unique_bytes": n_unique,
    }


def main():
    if len(sys.argv) < 3:
        print("usage: occam_c_decode_sweep.py <ckpt_path> <out_json>", file=sys.stderr)
        sys.exit(2)
    ckpt_path = sys.argv[1]
    out_path = Path(sys.argv[2])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    max_new = 80
    seed = 1337

    device = "cpu"
    torch.set_num_threads(max(1, os.cpu_count() - 2))
    print(f"[occam-c] device={device} threads={torch.get_num_threads()} torch={torch.__version__}", flush=True)

    t0 = time.time()
    model, cfg = load_model(ckpt_path, device=device)
    t_load = time.time() - t0
    n_params = sum(p.numel() for p in model.parameters())
    print(f"[occam-c] n_params={n_params:,} load_wall={t_load:.1f}s", flush=True)

    out = {
        "test": "OCCAM-C / Test #8 decode sweep",
        "ckpt": str(ckpt_path),
        "cell": "vJ",
        "n_params": n_params,
        "cfg": cfg,
        "max_new_tokens": max_new,
        "device": device,
        "load_wall_s": t_load,
        "results": [],
        "summary": {},
    }

    total_gens = len(CONFIGS) * len(PROBES)
    cnt = 0
    t_sweep_start = time.time()
    for config_name, config in CONFIGS:
        for probe_name, prompt_bytes in PROBES:
            cnt += 1
            t_probe = time.time()
            try:
                rec = run_single_probe(model, config_name, config, probe_name, prompt_bytes, max_new, device, seed)
            except Exception as e:
                rec = {
                    "config": config_name, "probe": probe_name,
                    "prompt_repr": repr(prompt_bytes)[:200],
                    "error": str(e),
                    "non_trivial": False,
                }
            rec["wall_s"] = time.time() - t_probe
            out["results"].append(rec)
            print(f"[occam-c] {cnt:3d}/{total_gens} {config_name:14s} {probe_name:16s} "
                  f"wall={rec['wall_s']:5.1f}s "
                  f"nt={int(rec.get('non_trivial', False))} "
                  f"ws={rec.get('whitespace_frac', -1):.2f} "
                  f"top={rec.get('top_byte_frac', -1):.2f} "
                  f"uniq={rec.get('n_unique_bytes', -1)} "
                  f"head={rec.get('leading_8_ids', [])[:6]}", flush=True)
            # persist incrementally so partial progress is saved
            if cnt % 8 == 0 or cnt == total_gens:
                with open(out_path, "w") as f:
                    json.dump(out, f, indent=2, ensure_ascii=False)
    out["sweep_wall_s"] = time.time() - t_sweep_start

    # summary: count non-trivial generations per config
    by_config = {}
    for rec in out["results"]:
        c = rec["config"]
        by_config.setdefault(c, {"non_trivial": 0, "total": 0, "mean_uniq": 0.0})
        by_config[c]["total"] += 1
        if rec.get("non_trivial"):
            by_config[c]["non_trivial"] += 1
        by_config[c]["mean_uniq"] += rec.get("n_unique_bytes", 0)
    for c, d in by_config.items():
        d["mean_uniq"] = d["mean_uniq"] / max(1, d["total"])
        d["non_trivial_rate"] = d["non_trivial"] / max(1, d["total"])
    out["summary"]["by_config"] = by_config

    with open(out_path, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"\n[occam-c] DONE wrote {out_path}", flush=True)
    print(f"[occam-c] sweep_wall={out['sweep_wall_s']:.1f}s", flush=True)
    print(f"[occam-c] summary:", flush=True)
    for c, d in by_config.items():
        print(f"   {c:14s} non_trivial={d['non_trivial']}/{d['total']} ({d['non_trivial_rate']*100:.0f}%)  mean_uniq={d['mean_uniq']:.1f}", flush=True)


if __name__ == "__main__":
    main()
