"""CLMv4Config — HF PretrainedConfig for CLM v4 base.

Generated by tool/transient_py/clm_v4_hf_format_shim.py (BG-Β 2026-05-04).
Mirrors ConsciousDecoderV3 hparams from ready/anima/models/legacy/decoder_v3.py.
"""

from transformers import PretrainedConfig


class CLMv4Config(PretrainedConfig):
    model_type = "clm_v4"

    def __init__(
        self,
        vocab_size: int = 64000,
        d_model: int = 768,
        n_layer: int = 16,
        n_head: int = 6,
        n_kv_head: int = 2,
        block_size: int = 512,
        consciousness_dim: int = 192,
        dropout: float = 0.0,
        gate_strength: float = 0.001,
        n_ca_rules: int = 8,
        # HF-standard aliases for compatibility with tooling that expects
        # `hidden_size` / `num_hidden_layers` / `num_attention_heads` etc.
        hidden_size: int = 768,
        num_hidden_layers: int = 16,
        num_attention_heads: int = 6,
        num_key_value_heads: int = 2,
        max_position_embeddings: int = 512,
        tie_word_embeddings: bool = True,
        bos_token_id: int = 1,
        eos_token_id: int = 2,
        pad_token_id: int = 0,
        **kwargs,
    ):
        self.vocab_size = vocab_size
        self.d_model = d_model
        self.n_layer = n_layer
        self.n_head = n_head
        self.n_kv_head = n_kv_head
        self.block_size = block_size
        self.consciousness_dim = consciousness_dim
        self.dropout = dropout
        self.gate_strength = gate_strength
        self.n_ca_rules = n_ca_rules
        self.hidden_size = hidden_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.max_position_embeddings = max_position_embeddings
        self.tie_word_embeddings = tie_word_embeddings
        super().__init__(
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            pad_token_id=pad_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )
