"""CLMv4ForCausalLM — HF PreTrainedModel wrapper for ConsciousDecoderV3.

Generated by tool/transient_py/clm_v4_hf_format_shim.py (BG-Β 2026-05-04).

This wraps the legacy ConsciousDecoderV3 (530M, 16-layer, GQA+RoPE+SwiGLU
+PureFieldFFN+CrossAttn+CA-rules+dual-heads). For lm-eval next-token use,
forward returns CausalLMOutputWithPast(logits=logits_a) and discards
logits_g + tensions (training-only signals).

The wrapped decoder is ConsciousDecoderV3 from ready/anima/models/legacy/
decoder_v3.py. To make this `trust_remote_code=True` self-contained, the
shim copies the decoder source files alongside this modeling file at save
time — see clm_v4_hf_format_shim.py:_copy_legacy_sources().
"""

from typing import Optional, Tuple, List, Union

import torch
import torch.nn as nn
from transformers import PreTrainedModel
from transformers.modeling_outputs import CausalLMOutputWithPast

from .configuration_clm_v4 import CLMv4Config

# Legacy decoder imports — files are copied into the same directory as this
# modeling file at save time (decoder_v3.py + conscious_decoder.py +
# consciousness_laws.py). HF trust_remote_code resolves these as part of
# the model package.
#
# v3: HF's `get_cached_module_file` only copies FIRST-LEVEL relative imports
# from the module pointed to by auto_map. We therefore explicitly import
# .conscious_decoder + .consciousness_laws here so HF copies them into the
# transformers_modules cache. They are NOT used directly in this file —
# the actual class import happens via .decoder_v3 — but the side-effect is
# what propagates the cache copy.
# NOTE: HF's get_relative_imports regex matches ONLY `from .xxx import yyy`
# patterns (and `import .xxx`); `from . import xxx` does NOT match. So we
# explicitly import a sentinel name from each sibling module here to trigger
# HF first-level relative-import discovery + cache-copy.
# consciousness_laws.py is INTENTIONALLY NOT imported here — the file is
# not copied to output_dir (it has a JSON-file dep that breaks under HF
# cache copy), and decoder_v3.py wraps its own consciousness_laws import in
# try/except with constant fallbacks (so absence is silently tolerated).
from .conscious_decoder import RMSNorm as _v3_force_conscious_decoder  # noqa: F401

try:
    from .decoder_v3 import ConsciousDecoderV3  # type: ignore
except ImportError as _e:  # noqa
    # Fallback: try direct import without package prefix (older HF versions)
    from decoder_v3 import ConsciousDecoderV3   # type: ignore


class CLMv4ForCausalLM(PreTrainedModel):
    config_class = CLMv4Config
    base_model_prefix = "decoder"
    supports_gradient_checkpointing = False
    _no_split_modules = ["DecoderBlockV2"]

    def __init__(self, config: CLMv4Config):
        super().__init__(config)
        self.config = config
        self.decoder = ConsciousDecoderV3(
            vocab_size=config.vocab_size,
            d_model=config.d_model,
            n_head=config.n_head,
            n_layer=config.n_layer,
            block_size=config.block_size,
            n_kv_head=config.n_kv_head,
            consciousness_dim=config.consciousness_dim,
            dropout=config.dropout,
            gate_strength=config.gate_strength,
            n_ca_rules=config.n_ca_rules,
        )
        # v3 P1 in-memory monkey-patch (mirror of on-disk decoder_v3.py P1
        # patch): when HF instantiates this wrapper from custom code, it
        # uses the cached transformers_modules/output/decoder_v3.py file
        # which already has the 4-tuple unpack patched. So no in-class
        # forward override needed.

        # post_init for HF housekeeping (does NOT re-init weights — they will
        # be loaded from safetensors right after construction).
        self.post_init()

    def _v3_invalidate_rope_caches(self):
        """v3 fix: RotaryPositionEmbedding is a bare Python class (NOT
        nn.Module), so its `register_inv_freq`/`_cos_cache`/`_sin_cache`
        attributes are not tracked by HF's meta-tensor mechanism. Under
        default low_cpu_mem_usage=True, these stay on meta after
        `from_pretrained`. Forward then fails because meta has no data.

        Workaround: after model is on real device, walk submodules and:
          1. Rebuild `register_inv_freq` from scratch (cheap: dim/2 floats).
          2. Clear `_cos_cache` / `_sin_cache` so they rebuild lazily.
        """
        import torch as _torch
        for module in self.decoder.blocks:
            attn = getattr(module, "attn", None)
            if attn is None or not hasattr(attn, "rope"):
                continue
            rope = attn.rope
            # Detect the device of any real param to anchor on
            try:
                anchor_device = next(p.device for p in attn.parameters()
                                      if p.device.type != "meta")
            except StopIteration:
                anchor_device = _torch.device("cpu")
            dim = rope.dim
            base = 10000.0
            inv_freq = 1.0 / (
                base ** (_torch.arange(0, dim, 2, device=anchor_device).float() / dim)
            )
            rope.register_inv_freq = inv_freq
            rope._cos_cache = None
            rope._sin_cache = None
            rope._cache_len = 0

    def _move_model_to_device(self, *args, **kwargs):
        # Hook used by HF accelerate path; clear RoPE caches after move.
        super()._move_model_to_device(*args, **kwargs) if hasattr(
            super(), "_move_model_to_device"
        ) else None
        self._v3_invalidate_rope_caches()

    def to(self, *args, **kwargs):
        out = super().to(*args, **kwargs)
        # After moving to real device, ensure RoPE caches are torn down so
        # the first forward rebuilds them on the new device.
        self._v3_invalidate_rope_caches()
        return out

    def get_input_embeddings(self):
        return self.decoder.tok_emb

    def set_input_embeddings(self, value):
        self.decoder.tok_emb = value
        # Re-tie head_a (weight tying invariant from ConsciousDecoderV3.__init__)
        self.decoder.head_a.weight = self.decoder.tok_emb.weight

    def get_output_embeddings(self):
        return self.decoder.head_a

    def set_output_embeddings(self, value):
        self.decoder.head_a = value

    def forward(
        self,
        input_ids: torch.LongTensor,
        attention_mask: Optional[torch.Tensor] = None,
        labels: Optional[torch.LongTensor] = None,
        consciousness_states: Optional[torch.Tensor] = None,
        return_dict: Optional[bool] = True,
        **kwargs,  # eat past_key_values, position_ids, etc.
    ) -> Union[Tuple, CausalLMOutputWithPast]:
        # ConsciousDecoderV3.forward signature: (idx, consciousness_states=None)
        # Returns: (logits_a, logits_g, tensions)
        #
        # v3 fix: Lazy RoPE-cache invalidation on first forward. We can't
        # rely on `.to()` being called (e.g., device_map="cpu" path uses
        # accelerate hooks that bypass it). Detect any meta tensor in the
        # RoPE caches and rebuild them synchronously here. Cheap (idempotent
        # after first valid forward).
        if not getattr(self, "_v3_rope_caches_validated", False):
            self._v3_invalidate_rope_caches()
            self._v3_rope_caches_validated = True

        # Block-size truncation: decoder asserts T <= block_size=512; if input
        # exceeds, we truncate from the LEFT (preserve recent context, matches
        # standard causal-LM eval convention for fixed-context models).
        B, T = input_ids.shape
        if T > self.config.block_size:
            input_ids = input_ids[:, -self.config.block_size:]
            if attention_mask is not None:
                attention_mask = attention_mask[:, -self.config.block_size:]

        logits_a, _logits_g, _tensions = self.decoder(
            input_ids, consciousness_states=consciousness_states
        )

        loss = None
        if labels is not None:
            # Standard causal-LM shift: predict token i+1 from position i
            shift_logits = logits_a[..., :-1, :].contiguous()
            shift_labels = labels[..., 1:].contiguous()
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_labels.view(-1),
            )

        if not return_dict:
            return (loss, logits_a) if loss is not None else (logits_a,)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits_a,
            past_key_values=None,   # decoder does not yet expose past_kv (TODO)
            hidden_states=None,
            attentions=None,
        )

    def prepare_inputs_for_generation(self, input_ids, past_key_values=None, **kwargs):
        # No KV-cache yet on ConsciousDecoderV3 — re-run from scratch each step.
        # lm-eval log-likelihood path does not need this; .generate() will be
        # slower but correct.
        return {"input_ids": input_ids}
