#!/usr/bin/env python3
"""
qmirror QRNG drop-in regression test — HMAC-DRBG (legacy) vs qmirror.qrng (new).

Reads:
  - HMAC-DRBG legacy stream:
      state/nexus_qrng_quantum_seed_2026_05_02/hmac_drbg_seed.json
      field: first_output_1024_bytes_hex (1024 bytes, IonQ-seeded HMAC-DRBG)
  - qmirror.qrng MOCK stream:
      state/qmirror_qrng_regression_2026_05_03/qmirror_mock_bytes.txt
      (one decimal byte per line, generated by qmirror_dump.hexa
       which mirrors qmirror.qrng _qrng_lcg_bytes(seed=12345))

Tests (NIST SP 800-22 tier-0 basics + drift comparison):
  - chi-square uniform on bytes (256 bins)
  - mean / variance / Shannon bit-entropy
  - lag-1 autocorrelation
  - byte-frequency drift (chi-square between two streams)

Outputs JSON to results.json and a one-page text summary.
"""
import json
import math
import os
import sys
from pathlib import Path

REPO = Path("/Users/ghost/core/anima")
STATE = REPO / "state" / "qmirror_qrng_regression_2026_05_03"
HMAC_REF = REPO / "state" / "nexus_qrng_quantum_seed_2026_05_02" / "hmac_drbg_seed.json"
HMAC_8192 = STATE / "hmac_drbg_legacy_bytes_8192.txt"
QMIRROR_8192 = STATE / "qmirror_mock_bytes_8192.txt"
QMIRROR_1024 = STATE / "qmirror_mock_bytes.txt"


def _load_decimal_bytes(p: Path) -> bytes:
    vals = []
    for line in p.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            v = int(line)
        except ValueError:
            continue
        if 0 <= v <= 255:
            vals.append(v)
    return bytes(vals)


def load_hmac_drbg() -> bytes:
    if HMAC_8192.exists():
        return _load_decimal_bytes(HMAC_8192)
    meta = json.loads(HMAC_REF.read_text())
    hex_str = meta["first_output_1024_bytes_hex"]
    raw = bytes.fromhex(hex_str)
    assert len(raw) == 1024, f"expected 1024 bytes, got {len(raw)}"
    return raw


def load_qmirror_mock() -> bytes:
    if QMIRROR_8192.exists():
        return _load_decimal_bytes(QMIRROR_8192)
    return _load_decimal_bytes(QMIRROR_1024)


def chi_square_uniform_256(b: bytes) -> tuple[float, float]:
    """Pearson chi-square vs uniform on 256 bins. Returns (chi2, p_value)."""
    n = len(b)
    expected = n / 256.0
    counts = [0] * 256
    for x in b:
        counts[x] += 1
    chi2 = sum((c - expected) ** 2 / expected for c in counts)
    # df = 255. Survival function approximation via Wilson-Hilferty.
    df = 255
    # WH transform: z = ((chi2/df)^(1/3) - (1 - 2/(9*df))) / sqrt(2/(9*df))
    t = (chi2 / df) ** (1 / 3.0)
    mu = 1 - 2.0 / (9 * df)
    sd = math.sqrt(2.0 / (9 * df))
    z = (t - mu) / sd
    # Two-sided not relevant for chi2; upper-tail p:
    # p = 1 - Phi(z)
    p = 0.5 * math.erfc(z / math.sqrt(2.0))
    return chi2, p


def mean_var(b: bytes) -> tuple[float, float]:
    n = len(b)
    m = sum(b) / n
    v = sum((x - m) ** 2 for x in b) / n
    return m, v


def shannon_bit_entropy(b: bytes) -> float:
    """Bit-level Shannon entropy in bits per bit."""
    n_bits = len(b) * 8
    n0 = 0
    for x in b:
        # popcount
        n0 += bin(x).count("1")
    n1 = n0
    n_zero = n_bits - n1
    if n1 == 0 or n_zero == 0:
        return 0.0
    p1 = n1 / n_bits
    p0 = 1 - p1
    return -(p0 * math.log2(p0) + p1 * math.log2(p1))


def shannon_byte_entropy(b: bytes) -> float:
    """Byte-level Shannon entropy in bits per byte (max 8.0)."""
    n = len(b)
    counts = [0] * 256
    for x in b:
        counts[x] += 1
    h = 0.0
    for c in counts:
        if c == 0:
            continue
        p = c / n
        h -= p * math.log2(p)
    return h


def autocorr_lag1(b: bytes) -> float:
    n = len(b)
    m = sum(b) / n
    num = sum((b[i] - m) * (b[i + 1] - m) for i in range(n - 1))
    den = sum((x - m) ** 2 for x in b)
    if den == 0:
        return 0.0
    return num / den


def runs_test_bits(b: bytes) -> tuple[float, float, int]:
    """NIST SP 800-22 Frequency (Monobit) + Runs test on bit sequence.
    Returns (monobit_p, runs_p, n_bits)."""
    bits = []
    for x in b:
        for k in range(7, -1, -1):
            bits.append((x >> k) & 1)
    n = len(bits)
    s = sum(2 * bi - 1 for bi in bits)
    s_obs = abs(s) / math.sqrt(n)
    monobit_p = math.erfc(s_obs / math.sqrt(2.0))
    # Pre-test
    pi = sum(bits) / n
    if abs(pi - 0.5) >= 2.0 / math.sqrt(n):
        return monobit_p, 0.0, n
    v = 1 + sum(1 for i in range(n - 1) if bits[i] != bits[i + 1])
    num = abs(v - 2 * n * pi * (1 - pi))
    den = 2 * math.sqrt(2 * n) * pi * (1 - pi)
    runs_p = math.erfc(num / den) if den > 0 else 0.0
    return monobit_p, runs_p, n


def chi_square_two_sample_256(a: bytes, c: bytes) -> tuple[float, float]:
    """Pearson chi-square between two byte distributions on 256 bins."""
    counts_a = [0] * 256
    counts_c = [0] * 256
    for x in a:
        counts_a[x] += 1
    for x in c:
        counts_c[x] += 1
    na, nc = len(a), len(c)
    chi2 = 0.0
    for i in range(256):
        ai, ci = counts_a[i], counts_c[i]
        tot = ai + ci
        if tot == 0:
            continue
        ea = tot * na / (na + nc)
        ec = tot * nc / (na + nc)
        if ea > 0:
            chi2 += (ai - ea) ** 2 / ea
        if ec > 0:
            chi2 += (ci - ec) ** 2 / ec
    df = 255
    t = (chi2 / df) ** (1 / 3.0)
    mu = 1 - 2.0 / (9 * df)
    sd = math.sqrt(2.0 / (9 * df))
    z = (t - mu) / sd
    p = 0.5 * math.erfc(z / math.sqrt(2.0))
    return chi2, p


def evaluate_stream(name: str, b: bytes) -> dict:
    chi2, p_uni = chi_square_uniform_256(b)
    m, v = mean_var(b)
    bit_h = shannon_bit_entropy(b)
    byte_h = shannon_byte_entropy(b)
    ac1 = autocorr_lag1(b)
    mono_p, runs_p, n_bits = runs_test_bits(b)
    return {
        "name": name,
        "n_bytes": len(b),
        "n_bits": n_bits,
        "chi2_uniform_256": chi2,
        "chi2_uniform_p_value": p_uni,
        "mean": m,
        "variance": v,
        "shannon_bit_entropy_bits_per_bit": bit_h,
        "shannon_byte_entropy_bits_per_byte": byte_h,
        "autocorrelation_lag1": ac1,
        "nist_monobit_p_value": mono_p,
        "nist_runs_p_value": runs_p,
    }


def verdict(s: dict, name: str) -> tuple[str, list[str]]:
    """PASS/PARTIAL/FAIL gate at alpha=0.01 on the basic NIST tier-0 tests."""
    notes = []
    pass_ = True
    if not (0.4 < s["chi2_uniform_p_value"] or s["chi2_uniform_p_value"] >= 0.01):
        # Actually only require > 0.01 (NIST default)
        pass
    if s["chi2_uniform_p_value"] < 0.01:
        pass_ = False
        notes.append(f"{name}: chi2 uniform p={s['chi2_uniform_p_value']:.4f} < 0.01")
    if s["nist_monobit_p_value"] < 0.01:
        pass_ = False
        notes.append(f"{name}: monobit p={s['nist_monobit_p_value']:.4f} < 0.01")
    if s["nist_runs_p_value"] < 0.01:
        pass_ = False
        notes.append(f"{name}: runs p={s['nist_runs_p_value']:.4f} < 0.01")
    if abs(s["mean"] - 127.5) > 10.0:
        pass_ = False
        notes.append(f"{name}: mean drift |{s['mean']:.2f}-127.5|>10")
    if s["shannon_bit_entropy_bits_per_bit"] < 0.99:
        pass_ = False
        notes.append(
            f"{name}: bit entropy {s['shannon_bit_entropy_bits_per_bit']:.4f} < 0.99"
        )
    # Confidence-interval-based lag-1 threshold: 99% CI ≈ 2.576/sqrt(n)
    # (Bartlett's formula for white-noise null). For n=1024 → ~0.0805.
    n = s["n_bytes"]
    ac_thresh = 2.576 / math.sqrt(n)
    if abs(s["autocorrelation_lag1"]) > ac_thresh:
        pass_ = False
        notes.append(
            f"{name}: |lag-1 autocorr|={abs(s['autocorrelation_lag1']):.4f} > "
            f"99%-CI threshold {ac_thresh:.4f} (Bartlett, n={n})"
        )
    return ("PASS" if pass_ else "FAIL"), notes


def main():
    hmac_b = load_hmac_drbg()
    qmir_b = load_qmirror_mock()
    s_hmac = evaluate_stream("hmac_drbg_legacy", hmac_b)
    s_qmir = evaluate_stream("qmirror_qrng_mock", qmir_b)
    v_hmac, n_hmac = verdict(s_hmac, "hmac_drbg")
    v_qmir, n_qmir = verdict(s_qmir, "qmirror_mock")
    # Also evaluate at n=1024 for the canonical regression contract size
    hmac_1024 = hmac_b[:1024]
    qmir_1024 = qmir_b[:1024]
    s_hmac_1024 = evaluate_stream("hmac_drbg_legacy_1024", hmac_1024)
    s_qmir_1024 = evaluate_stream("qmirror_qrng_mock_1024", qmir_1024)
    v_hmac_1024, n_hmac_1024 = verdict(s_hmac_1024, "hmac_drbg_1024")
    v_qmir_1024, n_qmir_1024 = verdict(s_qmir_1024, "qmirror_mock_1024")

    drift_chi2, drift_p = chi_square_two_sample_256(hmac_b, qmir_b)
    drift_pass = drift_p >= 0.01
    drift_chi2_1024, drift_p_1024 = chi_square_two_sample_256(hmac_1024, qmir_1024)
    drift_pass_1024 = drift_p_1024 >= 0.01

    # Drop-in verdict policy (regression == public-API + distributional drop-in,
    # NOT cryptographic equivalence):
    #   PASS    : drift two-sample chi-square passes at both sizes AND both
    #             streams pass NIST tier-0 at both sizes
    #   PARTIAL: drift passes (distributions indistinguishable) but at least
    #             one stream fails NIST tier-0 at one of the two sizes
    #             (acceptable for the MOCK fixture path; live ANU is the
    #             production source)
    #   FAIL   : two-sample drift detected (distributional shape mismatch)
    drift_ok = drift_pass_1024 and drift_pass
    indiv_ok = (
        v_hmac == "PASS" and v_qmir == "PASS"
        and v_hmac_1024 == "PASS" and v_qmir_1024 == "PASS"
    )
    if not drift_ok:
        overall = "FAIL"
    elif indiv_ok:
        overall = "PASS"
    else:
        overall = "PARTIAL"

    cond4 = "met" if overall == "PASS" else (
        "partially_met" if overall == "PARTIAL" else "unmet"
    )

    out = {
        "test": "qmirror_qrng_drop_in_regression_vs_hmac_drbg",
        "date": "2026-05-03",
        "alpha": 0.01,
        "n_bytes_per_stream": len(hmac_b),
        "streams_8192": {
            "hmac_drbg_legacy": s_hmac,
            "qmirror_qrng_mock": s_qmir,
        },
        "streams_1024": {
            "hmac_drbg_legacy": s_hmac_1024,
            "qmirror_qrng_mock": s_qmir_1024,
        },
        "verdicts": {
            "hmac_drbg_legacy_8192": v_hmac,
            "qmirror_qrng_mock_8192": v_qmir,
            "hmac_drbg_legacy_1024": v_hmac_1024,
            "qmirror_qrng_mock_1024": v_qmir_1024,
            "drop_in_regression": overall,
            "cond4_recommendation": cond4,
        },
        "drift_two_sample_chi2_8192": {
            "chi2": drift_chi2,
            "p_value": drift_p,
            "pass_at_alpha_0_01": drift_pass,
            "note": "Two-sample chi-square comparing byte distributions of the two streams (n=8192).",
        },
        "drift_two_sample_chi2_1024": {
            "chi2": drift_chi2_1024,
            "p_value": drift_p_1024,
            "pass_at_alpha_0_01": drift_pass_1024,
            "note": "Two-sample chi-square at canonical contract size (n=1024).",
        },
        "fail_notes_8192": n_hmac + n_qmir,
        "fail_notes_1024": n_hmac_1024 + n_qmir_1024,
        "sources": {
            "hmac_drbg_path": str(HMAC_REF),
            "qmirror_mock_path": str(QMIRROR_8192 if QMIRROR_8192.exists() else QMIRROR_1024),
            "hmac_drbg_8192_path": str(HMAC_8192),
        },
        "honest_caveats": [
            "Tier-0 NIST 800-22 only (monobit + runs + chi-uniform); Tier-1+ tests "
            "(block frequency, FFT spectral, longest-run, BBT, serial, approximate entropy, "
            "Maurer's universal, linear complexity, cumulative sums, random excursions, "
            "random excursions variant) NOT executed at this size — 1024 bytes (8192 bits) is "
            "below the recommended n>=1e6 bits for full SP 800-22 battery.",
            "MOCK fixture (LCG seed=12345) is byte-deterministic and shares no entropy with "
            "live ANU vacuum-fluctuation source. Live-vs-live comparison requires "
            "NEXUS_QMIRROR_LIVE=1 + NEXUS_QMIRROR_ANU_KEY and a fresh IonQ HMAC-DRBG "
            "instantiation; this run is the canonical CI regression check only.",
            "Statistical equivalence is NOT cryptographic equivalence: HMAC-DRBG provides "
            "forward/backward security under SHA-256 PRF assumption; qmirror MOCK is a Park-"
            "Miller-class LCG with trivial state recovery and zero crypto strength. The "
            "drop-in claim is for distributional shape only, not for keying material.",
        ],
    }

    out_json = STATE / "regression_results.json"
    out_json.write_text(json.dumps(out, indent=2))

    # Text summary
    lines = []
    lines.append("=" * 72)
    lines.append("qmirror QRNG drop-in regression vs HMAC-DRBG (legacy)")
    lines.append("=" * 72)
    for s in (s_hmac_1024, s_qmir_1024, s_hmac, s_qmir):
        lines.append(f"\n[{s['name']}] n_bytes={s['n_bytes']}")
        lines.append(f"  chi2_uniform_256  = {s['chi2_uniform_256']:8.2f}  p={s['chi2_uniform_p_value']:.4f}")
        lines.append(f"  mean              = {s['mean']:.4f}  (uniform expect 127.5)")
        lines.append(f"  variance          = {s['variance']:.2f}  (uniform expect 5461.25)")
        lines.append(f"  bit_entropy       = {s['shannon_bit_entropy_bits_per_bit']:.6f} bits/bit")
        lines.append(f"  byte_entropy      = {s['shannon_byte_entropy_bits_per_byte']:.4f} bits/byte (max 8)")
        lines.append(f"  autocorr_lag1     = {s['autocorrelation_lag1']:+.4f}")
        lines.append(f"  monobit_p         = {s['nist_monobit_p_value']:.4f}")
        lines.append(f"  runs_p            = {s['nist_runs_p_value']:.4f}")
    lines.append("\nDrift (two-sample chi-square between streams):")
    lines.append(f"  n=1024: chi2={drift_chi2_1024:.2f}  p={drift_p_1024:.4f}  pass(α=0.01)={drift_pass_1024}")
    lines.append(f"  n=8192: chi2={drift_chi2:.2f}  p={drift_p:.4f}  pass(α=0.01)={drift_pass}")
    lines.append("\nPer-stream verdicts (alpha=0.01, NIST tier-0 + mean/entropy/autocorr):")
    lines.append(f"  hmac_drbg_legacy   n=1024: {v_hmac_1024}")
    lines.append(f"  qmirror_qrng_mock  n=1024: {v_qmir_1024}")
    lines.append(f"  hmac_drbg_legacy   n=8192: {v_hmac}")
    lines.append(f"  qmirror_qrng_mock  n=8192: {v_qmir}")
    lines.append(f"\n  DROP-IN REGRESSION (overall): {overall}")
    lines.append(f"  cond.4 recommendation: {cond4}")
    notes = (n_hmac_1024 + n_qmir_1024 + n_hmac + n_qmir)
    if notes:
        lines.append("\nFail notes:")
        for n in notes:
            lines.append(f"  - {n}")
    summary = "\n".join(lines) + "\n"
    (STATE / "regression_summary.txt").write_text(summary)
    print(summary)
    return 0 if overall in ("PASS", "PARTIAL") else 1


if __name__ == "__main__":
    sys.exit(main())
