#!/usr/bin/env python3
# analyze_wrapper helper -- auto-generated by anima-eeg/protocols/analyze_wrapper.hexa
# raw#9 OK: /tmp-style transient (state/.analyze_wrapper_npy_helper.py).
# raw#37: re-written every invocation.
# raw#82: darwin-native venv-eeg python; no remote dispatch.
#
# CONTRACT
#   Loads a BrainFlow-captured .npy file, extracts 16 EEG channels in the
#   Cyton+Daisy standard layout (rows 1..16 when raw shape is 32xN, falls
#   back to direct 16xN), and computes per-channel rail saturation audit.
#
#   Algorithm mirrors anima-eeg/analyze.hexa::detect_railed_channels(...):
#     - rail_thresh_uv:   |sample| >= this -> saturated sample
#     - sat_frac_thresh:  if saturated_count / n > this -> RAILED
#     - DC drift check:   |mean(channel)| > 0.5 * rail_thresh_uv -> RAILED
#     - 1-based channel indices in output (matches analyze.hexa convention)
#
#   raw#10 honest: source-of-truth thresholds live in analyze.hexa
#   (RAIL_THRESH_UV_DEFAULT=187.0, SAT_FRAC_THRESH_DEFAULT=0.05,
#   DC_DRIFT_FRAC_OF_RAIL=0.5). Helper accepts overrides via CLI.
#
# USAGE
#   helper.py real <input.npy> <out.txt> <rail_thresh_uv> <sat_frac_thresh>
#   helper.py selftest <kind> <out.txt> <rail_thresh_uv> <sat_frac_thresh>
#       kind = "v6_pattern"   -> 16ch where rows {1,5,6,8,16} are railed
#                                (matches v6 EC sibling-discovery pattern)
#       kind = "all_clean"    -> 16ch low-amp 10 Hz sinusoid (PASS)

import sys
import os
import math

try:
    import numpy as np
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n')
    sys.exit(10)

DC_DRIFT_FRAC_OF_RAIL = 0.5  # mirrors analyze.hexa


def usage_exit():
    sys.stderr.write(
        'usage: helper <mode> <src> <out.txt> <rail_thresh_uv> <sat_frac_thresh>\n')
    sys.exit(2)


if len(sys.argv) < 6:
    usage_exit()

mode = sys.argv[1]
src = sys.argv[2]
out_path = sys.argv[3]
try:
    rail_thresh_uv = float(sys.argv[4])
    sat_frac_thresh = float(sys.argv[5])
except Exception as e:
    sys.stderr.write('bad-thresh-arg: ' + repr(e) + '\n')
    sys.exit(2)


def load_eeg16(path):
    """Extract 16 EEG channels from a BrainFlow .npy capture.

    BrainFlow Cyton+Daisy layout: rows 0..N (N>=24), where index 0 is the
    package number and indices 1..16 are EEG channels. This matches the
    eeg_indices=[1..16] field in <input>.npy.meta.json.

    Falls back to direct 16xN if shape is already 16ch.
    """
    a = np.load(path, allow_pickle=False)
    if a.ndim != 2:
        raise RuntimeError('expected 2-D, got ndim=' + str(a.ndim))
    rows, cols = a.shape
    if rows == 16:
        return a, 16, cols, 'direct_16xN'
    if cols == 16:
        return a.T, 16, rows, 'transposed_Nx16'
    if rows >= 24 and cols > rows:
        # BrainFlow rows: [package_num, eeg1..eeg16, accel/aux..., timestamp]
        return a[1:17, :], 16, cols, 'brainflow_rows1to16_of_' + str(rows)
    if cols >= 24 and rows > cols:
        return a.T[1:17, :], 16, rows, 'brainflow_cols1to16_of_' + str(cols)
    raise RuntimeError('cannot infer 16-ch layout from ' + str(a.shape))


def detect_railed_channels(eeg, rail_thresh, sat_thresh):
    """Mirrors anima-eeg/analyze.hexa::detect_railed_channels (1-based idx)."""
    n_chan = eeg.shape[0]
    sat_fracs = []
    railed = []
    o1 = False
    o2 = False
    for ch in range(n_chan):
        series = eeg[ch, :]
        n_samples = series.shape[0]
        if n_samples == 0:
            sat_fracs.append(0.0)
            continue
        abs_series = np.abs(series)
        sat_count = int(np.sum(abs_series >= rail_thresh))
        frac = float(sat_count) / float(n_samples)
        sat_fracs.append(frac)
        mean_v = float(np.mean(series))
        dc_drift_railed = abs(mean_v) > (DC_DRIFT_FRAC_OF_RAIL * rail_thresh)
        peak_railed = frac > sat_thresh
        if peak_railed or dc_drift_railed:
            one_based = ch + 1
            railed.append(one_based)
            if one_based == 7:
                o1 = True
            if one_based == 8:
                o2 = True
    n_railed = len(railed)
    if n_railed == 0:
        status = 'PASS'
    elif n_railed <= 3:
        status = 'WARN'
    else:
        status = 'FAIL'
    if o1 and o2:
        tier = 'insufficient_data'
    elif o1 or o2:
        tier = 'functional'
    elif status == 'FAIL':
        tier = 'functional'
    else:
        tier = 'full'
    return {
        'status': status,
        'tier': tier,
        'n_total': n_chan,
        'n_railed': n_railed,
        'railed': railed,
        'sat_fracs': sat_fracs,
        'o1_railed': o1,
        'o2_railed': o2,
    }


def synthetic_v6_pattern(rail_uv):
    """16ch fixture matching v6 EC sibling-discovery: rows {1,5,6,8,16} railed.

    Mirrors analyze.hexa::fixture_16ch_with_railed at fs=125, n=7500
    (60s capture). Rail rows are pinned to +rail_uv; clean rows have a
    low-amplitude 10 Hz sinusoid (~1 µV).
    """
    fs = 125.0
    n = 7500
    rail_rows = {1, 5, 6, 8, 16}
    eeg = np.zeros((16, n), dtype=np.float64)
    t = np.arange(n) / fs
    clean = 1.0 * np.sin(2.0 * math.pi * 10.0 * t)
    for ch in range(16):
        one_based = ch + 1
        if one_based in rail_rows:
            eeg[ch, :] = rail_uv
        else:
            eeg[ch, :] = clean
    return eeg, 'synthetic_v6_pattern_fs125_n7500'


def synthetic_all_clean():
    fs = 125.0
    n = 7500
    eeg = np.zeros((16, n), dtype=np.float64)
    t = np.arange(n) / fs
    for ch in range(16):
        eeg[ch, :] = 1.0 * np.sin(2.0 * math.pi * 10.0 * t)
    return eeg, 'synthetic_all_clean_fs125_n7500'


if mode == 'real':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n')
        sys.exit(4)
    eeg, n_ch, n_samp, layout = load_eeg16(src)
    src_label = src
elif mode == 'selftest':
    if src == 'v6_pattern':
        eeg, layout = synthetic_v6_pattern(rail_thresh_uv + 13.0)
    elif src == 'all_clean':
        eeg, layout = synthetic_all_clean()
    else:
        sys.stderr.write('unknown-selftest-kind: ' + src + '\n')
        sys.exit(3)
    n_ch, n_samp = eeg.shape
    src_label = 'selftest:' + src
else:
    sys.stderr.write('unknown-mode: ' + mode + '\n')
    sys.exit(2)

audit = detect_railed_channels(eeg, rail_thresh_uv, sat_frac_thresh)

# Write structured output (key=value lines + JSON sidecar fragment)
with open(out_path, 'w') as f:
    f.write('schema=analyze_wrapper_rail_audit_v1\n')
    f.write('mode=' + mode + '\n')
    f.write('src=' + src_label + '\n')
    f.write('layout=' + layout + '\n')
    f.write('n_ch=' + str(int(n_ch)) + '\n')
    f.write('n_samp=' + str(int(n_samp)) + '\n')
    f.write('rail_thresh_uv=' + ('%.6f' % rail_thresh_uv) + '\n')
    f.write('sat_frac_thresh=' + ('%.6f' % sat_frac_thresh) + '\n')
    f.write('rail_status=' + audit['status'] + '\n')
    f.write('rail_verdict_tier=' + audit['tier'] + '\n')
    f.write('rail_n_total=' + str(audit['n_total']) + '\n')
    f.write('rail_n_railed=' + str(audit['n_railed']) + '\n')
    f.write('rail_o1_railed=' + ('1' if audit['o1_railed'] else '0') + '\n')
    f.write('rail_o2_railed=' + ('1' if audit['o2_railed'] else '0') + '\n')
    # railed channels as comma-separated 1-based indices (no brackets)
    f.write('rail_railed_csv=' + ','.join(str(x) for x in audit['railed']) + '\n')
    # display string with brackets to match analyze.hexa::rail_railed_list_str
    if audit['railed']:
        disp = '[' + ', '.join(str(x) for x in audit['railed']) + ']'
    else:
        disp = '[]'
    f.write('rail_railed_disp=' + disp + '\n')
    # per-channel saturation fractions, comma-separated, 6dp
    f.write('rail_sat_fracs_csv=' + ','.join(
        ('%.6f' % x) for x in audit['sat_fracs']) + '\n')
    # clean-channels (1..16 minus railed) for --clean-channels-auto
    railed_set = set(audit['railed'])
    clean_list = [i for i in range(1, audit['n_total'] + 1) if i not in railed_set]
    f.write('rail_clean_csv=' + ','.join(str(x) for x in clean_list) + '\n')
    if clean_list:
        clean_disp = '[' + ', '.join(str(x) for x in clean_list) + ']'
    else:
        clean_disp = '[]'
    f.write('rail_clean_disp=' + clean_disp + '\n')

# stdout: short OK line for hexa exec_with_status capture
print('OK status=' + audit['status']
      + ' n_railed=' + str(audit['n_railed']) + '/' + str(audit['n_total'])
      + ' railed=' + ('[' + ','.join(str(x) for x in audit['railed']) + ']'))
