#!/usr/bin/env python3
# clm_eeg_berger_sanity helper — auto-generated by anima-clm-eeg/tool/clm_eeg_berger_sanity.hexa
# raw#9 OK: this is the /tmp-style transient .py helper (state/.berger_sanity_helper.py).
# raw#37: re-written every invocation; do NOT edit by hand — edits are clobbered.
# raw#82: darwin-native venv-eeg python invocation only; no remote dispatch.
import sys, os
try:
    import numpy as np
    from scipy import signal, integrate
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n'); sys.exit(10)

if len(sys.argv) < 4:
    sys.stderr.write('usage: helper <mode> <input_or_kind> <out.txt>\n')
    sys.stderr.write('   mode = real | selftest\n')
    sys.stderr.write('   selftest kinds: alpha | white | line50\n')
    sys.exit(2)

mode, src, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
fs = 125.0
nperseg = 512

def load_eeg16(path):
    a = np.load(path, allow_pickle=False)
    if a.ndim != 2:
        raise RuntimeError('expected 2-D .npy, got ndim=' + str(a.ndim))
    rows, cols = a.shape
    if rows == 16:
        return a, rows, cols
    if cols == 16:
        return a.T, 16, rows
    if rows >= 32 and cols > rows:
        # BrainFlow 32-row layout: indices 1..16 are EEG (0-indexed slice 1:17)
        return a[1:17, :], 16, cols
    if cols >= 32 and rows > cols:
        return a.T[1:17, :], 16, rows
    raise RuntimeError('cannot infer 16-ch layout from shape ' + str(a.shape))

if mode == 'selftest':
    kind = src
    n = 60 * int(fs)  # 60 s
    rng = np.random.RandomState(42)
    eeg = np.zeros((16, n), dtype=np.float64)
    t = np.arange(n) / fs
    for ch in range(16):
        eeg[ch, :] = rng.normal(0, 1.0, size=n).astype(np.float64)
    if kind == 'alpha':
        # Inject 10 Hz alpha rhythm on O1, O2 (channel index 6, 7) — much
        # bigger amplitude than the white-noise floor so alpha clearly
        # dominates the band-power integral.
        for ch in [6, 7]:
            eeg[ch, :] = eeg[ch, :] + 8.0 * np.sin(2 * np.pi * 10.0 * t)
    elif kind == 'line50':
        for ch in [6, 7]:
            eeg[ch, :] = eeg[ch, :] + 8.0 * np.sin(2 * np.pi * 50.0 * t)
    elif kind == 'white':
        pass  # already white noise
    else:
        sys.stderr.write('unknown selftest kind: ' + kind + '\n'); sys.exit(3)
    n_ch, n_samp = 16, n
    sha = ''
elif mode == 'real':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n'); sys.exit(4)
    eeg, n_ch, n_samp = load_eeg16(src)
    sha = ''
else:
    sys.stderr.write('unknown mode: ' + mode + '\n'); sys.exit(2)

def welch_band(x):
    f, psd = signal.welch(x, fs=fs, nperseg=min(nperseg, len(x)))
    def bp(lo, hi):
        m = (f >= lo) & (f <= hi)
        if not np.any(m):
            return 0.0
        return float(integrate.simpson(psd[m], x=f[m]))
    delta = bp(1.0, 4.0)
    theta = bp(4.0, 8.0)
    alpha = bp(8.0, 13.0)
    beta  = bp(13.0, 30.0)
    # peak frequency restricted to 1..40 Hz
    m = (f >= 1.0) & (f <= 40.0)
    if not np.any(m):
        peak = 0.0
    else:
        peak = float(f[m][int(np.argmax(psd[m]))])
    return delta, theta, alpha, beta, peak

results = {}
for label, ch_idx in [('o1', 6), ('o2', 7)]:
    if ch_idx >= n_ch:
        sys.stderr.write('channel-index-out-of-range: ' + label + '\n'); sys.exit(5)
    delta, theta, alpha, beta, peak = welch_band(eeg[ch_idx, :])
    results[label] = (delta, theta, alpha, beta, peak)

# Frozen criteria (mirror of hexa SSOT) — recomputed in hexa from band powers,
# but also emitted here for self-check.
def evaluate(d, t_, a, b, peak):
    # uV^2 / Hz absolute scale is irrelevant since we compare ratios within ch
    c1 = 1 if a > b else 0
    c2 = 1 if a > 0.30 * d else 0
    c3 = 1 if (7.0 <= peak and peak <= 14.0) else 0
    return c1, c2, c3

with open(out_path, 'w') as f:
    f.write('schema=berger_sanity_v1\n')
    f.write('n_ch=' + str(int(n_ch)) + '\n')
    f.write('n_samp=' + str(int(n_samp)) + '\n')
    for lbl, ch_idx in [('o1', 6), ('o2', 7)]:
        d, t_, a, b, peak = results[lbl]
        c1, c2, c3 = evaluate(d, t_, a, b, peak)
        # Emit fixed-point integers for hexa parsing.
        # band power × 1e6 truncated to int (preserves ~6 sig digits).
        f.write(lbl + '_delta_x1e6=' + str(int(round(d * 1.0e6))) + '\n')
        f.write(lbl + '_theta_x1e6=' + str(int(round(t_ * 1.0e6))) + '\n')
        f.write(lbl + '_alpha_x1e6=' + str(int(round(a * 1.0e6))) + '\n')
        f.write(lbl + '_beta_x1e6='  + str(int(round(b * 1.0e6))) + '\n')
        f.write(lbl + '_peak_hz_x10=' + str(int(round(peak * 10.0))) + '\n')
        f.write(lbl + '_c1_pass=' + str(int(c1)) + '\n')
        f.write(lbl + '_c2_pass=' + str(int(c2)) + '\n')
        f.write(lbl + '_c3_pass=' + str(int(c3)) + '\n')

print('OK n_ch=' + str(int(n_ch)) + ' n_samp=' + str(int(n_samp)))
