#!/usr/bin/env python3
# berger_alpha_gate helper — auto-generated by anima-eeg-core/tool/modules/_gates/berger_alpha.hexa
# raw#9 OK transient .py helper; raw#37 re-written each call.
import sys, os
try:
    import numpy as np
    from scipy import signal, integrate
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n'); sys.exit(10)

if len(sys.argv) < 5:
    sys.stderr.write('usage: helper <mode> <input_or_kind> <fs> <out.txt>\n'); sys.exit(2)
mode, src, fs_s, out_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
fs = float(fs_s)
nperseg = 512

def load_eeg16(path):
    a = np.load(path, allow_pickle=False)
    if a.ndim != 2: raise RuntimeError('expected 2-D')
    r, c = a.shape
    if r == 16: return a, 16, c
    if c == 16: return a.T, 16, r
    if r >= 32 and c > r: return a[1:17, :], 16, c
    if c >= 32 and r > c: return a.T[1:17, :], 16, r
    raise RuntimeError('cannot infer 16-ch from ' + str(a.shape))

if mode == 'selftest':
    kind = src
    n = 60 * int(fs)
    rng = np.random.RandomState(42)
    eeg = np.zeros((16, n), dtype=np.float64)
    t = np.arange(n) / fs
    for ch in range(16):
        eeg[ch, :] = rng.normal(0, 1.0, size=n)
    if kind == 'alpha' or kind == 'awake':
        for ch in [6, 7]: eeg[ch, :] += 8.0 * np.sin(2 * np.pi * 10.0 * t)
    elif kind == 'line50':
        for ch in [6, 7]: eeg[ch, :] += 8.0 * np.sin(2 * np.pi * 50.0 * t)
    elif kind == 'drift':
        for ch in [6, 7]: eeg[ch, :] += 50.0 * np.sin(2 * np.pi * 0.05 * t)
    elif kind == 'white':
        pass
    else:
        sys.stderr.write('unknown kind: ' + kind + '\n'); sys.exit(3)
    n_ch, n_samp = 16, n
elif mode == 'real':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n'); sys.exit(4)
    eeg, n_ch, n_samp = load_eeg16(src)
else:
    sys.stderr.write('unknown mode\n'); sys.exit(2)

def welch_band(x):
    f, psd = signal.welch(x, fs=fs, nperseg=min(nperseg, len(x)))
    def bp(lo, hi):
        m = (f >= lo) & (f <= hi)
        return float(integrate.simpson(psd[m], x=f[m])) if np.any(m) else 0.0
    delta = bp(1.0, 4.0); theta = bp(4.0, 8.0)
    alpha = bp(8.0, 13.0); beta = bp(13.0, 30.0)
    m = (f >= 1.0) & (f <= 40.0)
    peak = float(f[m][int(np.argmax(psd[m]))]) if np.any(m) else 0.0
    return delta, theta, alpha, beta, peak

with open(out_path, 'w') as f:
    f.write('schema=berger_alpha_gate_v1\n')
    f.write('n_ch=' + str(int(n_ch)) + '\n')
    f.write('n_samp=' + str(int(n_samp)) + '\n')
    for lbl, ci in [('o1', 6), ('o2', 7)]:
        if ci >= n_ch: sys.stderr.write('ch-oob: ' + lbl + '\n'); sys.exit(5)
        d, t_, a, b, pk = welch_band(eeg[ci, :])
        f.write(lbl + '_delta_x1e6=' + str(int(round(d*1e6))) + '\n')
        f.write(lbl + '_alpha_x1e6=' + str(int(round(a*1e6))) + '\n')
        f.write(lbl + '_beta_x1e6='  + str(int(round(b*1e6))) + '\n')
        f.write(lbl + '_peak_hz_x10=' + str(int(round(pk*10))) + '\n')
        # ratios x1000
        ab = (a / b) if b > 0 else 0.0
        ad = (a / d) if d > 0 else 0.0
        f.write(lbl + '_alpha_beta_ratio_x1000=' + str(int(round(ab*1000))) + '\n')
        f.write(lbl + '_alpha_delta_ratio_x1000=' + str(int(round(ad*1000))) + '\n')
print('OK')
