#!/usr/bin/env python3
# eeg_anomaly_autoencoder helper — auto-generated by anima-clm-eeg/tool/eeg_anomaly_autoencoder.hexa
# raw#9 OK: state-local /tmp-style transient (state/.eeg_anom_helper.py).
# raw#37: re-written every invocation.
# raw#73: deterministic seeded numpy autoencoder; identical input → identical output.
# raw#82: darwin-native venv-eeg python (numpy + scipy + sklearn).
import sys, os, math, json
try:
    import numpy as np
    from scipy.signal import welch
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n'); sys.exit(10)

# ─── frozen hyperparameters (mirror .hexa) ───────────────────────────────
SAMPLE_RATE_HZ = 125
SEGMENT_SAMPLES = 5 * SAMPLE_RATE_HZ  # 625
N_CHANNELS = 16
BANDS = [(1.0, 4.0), (4.0, 8.0), (8.0, 13.0), (13.0, 30.0), (30.0, 45.0)]
N_BANDS = len(BANDS)
FEATURE_DIM = N_CHANNELS * N_BANDS
BOTTLENECK_DIM = 8
EPOCHS_MIN = 100
EPOCHS_MAX = 500
LR = 0.02
BATCH_SIZE = 16
Z_THRESHOLD = 2.0
SEED = 17
MIN_BASELINE_N = 50

if len(sys.argv) < 4:
    sys.stderr.write('usage: helper <mode> <kind|input.npy> <out.txt> [ablation_pca]\n')
    sys.exit(2)

mode = sys.argv[1]
src = sys.argv[2]
out_path = sys.argv[3]
ablation_pca = (len(sys.argv) >= 5 and sys.argv[4] == '1')

# ─── feature extraction ──────────────────────────────────────────────────
def segment_to_feature(seg):
    # seg shape (N_CHANNELS, SEGMENT_SAMPLES)
    feat = np.zeros((N_CHANNELS, N_BANDS), dtype=np.float64)
    for ch in range(N_CHANNELS):
        f, p = welch(seg[ch, :], fs=SAMPLE_RATE_HZ, nperseg=125, noverlap=0,
                     window='hann', detrend='constant')
        for j, (lo, hi) in enumerate(BANDS):
            mask = (f >= lo) & (f < hi)
            if mask.any():
                feat[ch, j] = np.log10(p[mask].sum() + 1e-12)
            else:
                feat[ch, j] = -12.0
    return feat.reshape(-1)

def features_from_segments(segs):
    X = np.zeros((len(segs), FEATURE_DIM), dtype=np.float64)
    for i, s in enumerate(segs):
        X[i, :] = segment_to_feature(s)
    return X

# ─── synthetic data (selftest) ──────────────────────────────────────────
def make_baseline_segments(n, rng):
    # Synthetic eyes-closed resting EEG: 1/f^alpha background + alpha rhythm.
    # Tight manifold: per-segment alpha-rhythm phase shared across channels
    # (frontoparietal alpha is broadly synchronous in resting EC); only noise
    # varies per channel. This produces stable per-band powers across
    # segments, mimicking real EEG band-power stability.
    segs = []
    for k in range(n):
        seg = np.zeros((N_CHANNELS, SEGMENT_SAMPLES), dtype=np.float64)
        t = np.arange(SEGMENT_SAMPLES) / SAMPLE_RATE_HZ
        seg_phase = rng.uniform(0, 2*np.pi, size=5)  # one phase per band, shared cross-ch
        for ch in range(N_CHANNELS):
            x = np.zeros(SEGMENT_SAMPLES)
            for j, f0 in enumerate((2.0, 5.0, 10.0, 18.0, 35.0)):
                amp = 1.5 / f0
                x += amp * np.sin(2*np.pi*f0*t + seg_phase[j])
            x += 0.03 * rng.normal(0, 1, SEGMENT_SAMPLES)
            x += 0.8 * np.sin(2*np.pi*10.0*t + seg_phase[2])
            seg[ch, :] = x
        segs.append(seg)
    return segs

def make_anomaly_segments(n, rng):
    # high-amplitude beta burst + step artifact (simulated motion)
    segs = []
    for k in range(n):
        seg = np.zeros((N_CHANNELS, SEGMENT_SAMPLES), dtype=np.float64)
        t = np.arange(SEGMENT_SAMPLES) / SAMPLE_RATE_HZ
        for ch in range(N_CHANNELS):
            x = 0.2 * rng.normal(0, 1, SEGMENT_SAMPLES)
            # huge beta burst — atypical of resting eyes-closed
            x += 5.0 * np.sin(2*np.pi*22.0*t + rng.uniform(0,2*np.pi))
            # transient step
            j = rng.randint(50, SEGMENT_SAMPLES - 50)
            x[j:j+30] += 8.0
            seg[ch, :] = x
        segs.append(seg)
    return segs

# ─── numpy autoencoder ───────────────────────────────────────────────────
def init_ae(rng):
    # Glorot/tanh init; layers: 80→40→20→8→20→40→80
    def w(in_d, out_d):
        lim = math.sqrt(6.0 / (in_d + out_d))
        return rng.uniform(-lim, lim, size=(in_d, out_d))
    P = {}
    P['W1'] = w(80, 40); P['b1'] = np.zeros(40)
    P['W2'] = w(40, 20); P['b2'] = np.zeros(20)
    P['W3'] = w(20, 8);  P['b3'] = np.zeros(8)
    P['W4'] = w(8, 20);  P['b4'] = np.zeros(20)
    P['W5'] = w(20, 40); P['b5'] = np.zeros(40)
    P['W6'] = w(40, 80); P['b6'] = np.zeros(80)
    return P

def forward(P, X):
    # tanh hidden, linear bottleneck and output
    z1 = X @ P['W1'] + P['b1']; a1 = np.tanh(z1)
    z2 = a1 @ P['W2'] + P['b2']; a2 = np.tanh(z2)
    z3 = a2 @ P['W3'] + P['b3']; a3 = z3  # linear bottleneck
    z4 = a3 @ P['W4'] + P['b4']; a4 = np.tanh(z4)
    z5 = a4 @ P['W5'] + P['b5']; a5 = np.tanh(z5)
    z6 = a5 @ P['W6'] + P['b6']; a6 = z6  # linear output
    cache = (X, a1, a2, a3, a4, a5, a6)
    return a6, cache

def backward(P, cache, Y):
    X, a1, a2, a3, a4, a5, a6 = cache
    n = X.shape[0]
    g = {}
    d6 = (a6 - Y) * (2.0 / n)                 # MSE deriv (linear out)
    g['W6'] = a5.T @ d6;  g['b6'] = d6.sum(0)
    d5 = (d6 @ P['W6'].T) * (1.0 - a5*a5)
    g['W5'] = a4.T @ d5;  g['b5'] = d5.sum(0)
    d4 = (d5 @ P['W5'].T) * (1.0 - a4*a4)
    g['W4'] = a3.T @ d4;  g['b4'] = d4.sum(0)
    d3 = d4 @ P['W4'].T                        # linear bottleneck
    g['W3'] = a2.T @ d3;  g['b3'] = d3.sum(0)
    d2 = (d3 @ P['W3'].T) * (1.0 - a2*a2)
    g['W2'] = a1.T @ d2;  g['b2'] = d2.sum(0)
    d1 = (d2 @ P['W2'].T) * (1.0 - a1*a1)
    g['W1'] = X.T @ d1;   g['b1'] = d1.sum(0)
    return g

def sgd_step(P, g, lr, wd=1e-2):
    # SGD with L2 weight decay on weight matrices (not biases). High wd
    # (1e-2) is needed for small N (~120 train) on an 80-d input to
    # prevent memorization (raw#71 F3).
    for k in P.keys():
        if k.startswith('W'):
            P[k] -= lr * (g[k] + wd * P[k])
        else:
            P[k] -= lr * g[k]

def mse(Yh, Y):
    return float(((Yh - Y) ** 2).mean())

def per_sample_recon_err(Yh, Y):
    return ((Yh - Y) ** 2).mean(axis=1)

def train_ae(Xtr, Xva, epochs_min, epochs_max, lr, batch, seed, flat_loss=False):
    rng = np.random.RandomState(seed)
    P = init_ae(rng)
    n = Xtr.shape[0]
    Yh0, _ = forward(P, Xtr)
    init_train_loss = mse(Yh0, Xtr)
    best_val = float('inf'); best_epoch = -1; patience = 25; bad = 0
    history = []
    if flat_loss:
        # F1 falsifier: 1 epoch and no SGD steps → loss should NOT decrease
        Yht, _ = forward(P, Xtr)
        Yhv, _ = forward(P, Xva)
        history.append((mse(Yht, Xtr), mse(Yhv, Xva)))
        return P, history, init_train_loss
    for epoch in range(epochs_max):
        idx = rng.permutation(n)
        for s in range(0, n, batch):
            b_idx = idx[s:s+batch]
            Xb = Xtr[b_idx]
            Yh, cache = forward(P, Xb)
            g = backward(P, cache, Xb)
            sgd_step(P, g, lr)
        Yht, _ = forward(P, Xtr); tr = mse(Yht, Xtr)
        Yhv, _ = forward(P, Xva); va = mse(Yhv, Xva)
        history.append((tr, va))
        if va < best_val - 1e-6:
            best_val = va; best_epoch = epoch; bad = 0
        else:
            bad += 1
        if epoch >= epochs_min and bad >= patience:
            break
    return P, history, init_train_loss

# ─── PCA(8) ablation (F4) ────────────────────────────────────────────────
def pca_recon_err(Xtr, Xte, k):
    mu = Xtr.mean(0)
    A = Xtr - mu
    # SVD
    U, S, Vt = np.linalg.svd(A, full_matrices=False)
    Vk = Vt[:k]
    Z = (Xte - mu) @ Vk.T
    Xh = Z @ Vk + mu
    return ((Xh - Xte) ** 2).mean(axis=1)

# ─── load real data ──────────────────────────────────────────────────────
def load_real_segments(path):
    a = np.load(path, allow_pickle=False)
    if a.ndim != 3:
        raise RuntimeError('expected 3-D (n_seg, 16, samples), got ndim=' + str(a.ndim))
    n, c, s = a.shape
    if c != N_CHANNELS:
        if s == N_CHANNELS:
            a = a.transpose(0, 2, 1)
            n, c, s = a.shape
        else:
            raise RuntimeError('cannot infer 16-ch axis from ' + str(a.shape))
    if s < SEGMENT_SAMPLES:
        raise RuntimeError('segment too short: ' + str(s))
    if s > SEGMENT_SAMPLES:
        a = a[:, :, :SEGMENT_SAMPLES]
    return [a[i] for i in range(n)]

# ─── dispatch by mode ────────────────────────────────────────────────────
flat_loss = False
tiny_n = False

if mode == 'selftest':
    kind = src
    rng = np.random.RandomState(SEED)
    if kind == 'baseline-only':
        baseline = make_baseline_segments(200, rng)
        injected = []
    elif kind == 'inject-anomaly':
        baseline = make_baseline_segments(200, rng)
        injected = make_anomaly_segments(20, rng)
    elif kind == 'flat-loss':
        baseline = make_baseline_segments(60, rng)
        injected = make_anomaly_segments(10, rng)
        flat_loss = True
    elif kind == 'tiny-n':
        baseline = make_baseline_segments(10, rng)
        injected = []
        tiny_n = True
    else:
        sys.stderr.write('unknown selftest kind: ' + kind + '\n'); sys.exit(3)
elif mode == 'real-train':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n'); sys.exit(4)
    baseline = load_real_segments(src)
    injected = []
    if len(baseline) < MIN_BASELINE_N:
        sys.stderr.write('insufficient-baseline: have ' + str(len(baseline))
                         + ' need ' + str(MIN_BASELINE_N) + '\n')
        sys.exit(5)
else:
    sys.stderr.write('unknown mode: ' + mode + '\n'); sys.exit(2)

# ─── feature extraction ──────────────────────────────────────────────────
X_base = features_from_segments(baseline)
X_inj  = features_from_segments(injected) if injected else np.zeros((0, FEATURE_DIM))

# train/val/calib split (60/20/20, deterministic)
rng_split = np.random.RandomState(SEED + 1)
n_base = X_base.shape[0]
perm = rng_split.permutation(n_base)
n_val = max(2, int(round(0.2 * n_base)))
n_cal = max(2, int(round(0.2 * n_base)))
val_idx = perm[:n_val]
cal_idx = perm[n_val:n_val + n_cal]
tr_idx  = perm[n_val + n_cal:]
Xtr_raw = X_base[tr_idx]
Xva_raw = X_base[val_idx]
Xcal_raw = X_base[cal_idx]

# z-score per feature (trained on Xtr only)
mu = Xtr_raw.mean(0)
sigma = Xtr_raw.std(0)
sigma = np.where(sigma < 1e-8, 1.0, sigma)
Xtr = (Xtr_raw - mu) / sigma
Xva = (Xva_raw - mu) / sigma
Xcal = (Xcal_raw - mu) / sigma
Xinj = ((X_inj - mu) / sigma) if X_inj.shape[0] > 0 else X_inj

# ─── train ───────────────────────────────────────────────────────────────
epochs_min_use = EPOCHS_MIN if not tiny_n else 30
P, history, init_train_loss = train_ae(Xtr, Xva, epochs_min_use, EPOCHS_MAX,
                                        LR, BATCH_SIZE, SEED, flat_loss=flat_loss)
final_train_loss = history[-1][0]
final_val_loss = history[-1][1]

# ─── reconstruction error baseline distribution ─────────────────────────
# Anchor mu_e, sigma_e on a HELD-OUT baseline pool (Xva), not the training
# set. Training-set errors are systematically optimistic (memorized) and
# would yield biased z-scores on real held-out segments.
Yh_tr, _ = forward(P, Xtr); err_tr = per_sample_recon_err(Yh_tr, Xtr)
Yh_va, _ = forward(P, Xva); err_va = per_sample_recon_err(Yh_va, Xva)
mu_e = float(err_va.mean())
sigma_e = float(err_va.std())
if sigma_e < 1e-12: sigma_e = 1e-12

def zscore(e): return (e - mu_e) / sigma_e

# C3: held-out CALIBRATION (separate from val) — fraction with z ≤ 2
Yh_cal, _ = forward(P, Xcal); err_cal = per_sample_recon_err(Yh_cal, Xcal)
z_cal = zscore(err_cal)
c3_ok_frac = float((z_cal <= Z_THRESHOLD).mean())

# C4: injected anomaly median z
if Xinj.shape[0] > 0:
    Yh_inj, _ = forward(P, Xinj); err_inj = per_sample_recon_err(Yh_inj, Xinj)
    z_inj = zscore(err_inj)
    c4_inject_median_z = float(np.median(z_inj))
    c4_inject_n = int(z_inj.shape[0])
    c4_inject_flag_frac = float((z_inj > Z_THRESHOLD).mean())
else:
    c4_inject_median_z = float('nan')
    c4_inject_n = 0
    c4_inject_flag_frac = float('nan')

# C5: re-eval on training set, fraction self-flagged
z_tr = zscore(err_tr)
c5_reeval_flag_frac = float((z_tr > Z_THRESHOLD).mean())

# ─── F4 ablation: PCA(8) AUC vs AE AUC on injected vs baseline ──────────
ae_auc = float('nan'); pca_auc = float('nan')
if Xinj.shape[0] > 0 and ablation_pca:
    # AUC: probability that a random injected has higher err than a random baseline
    e_pos = err_inj
    e_neg = err_cal
    def auc_score(pos, neg):
        if len(pos) == 0 or len(neg) == 0: return float('nan')
        c = 0; t = 0
        for x in pos:
            for y in neg:
                t += 1
                if x > y: c += 1
                elif x == y: c += 0.5
        return c / max(1, t)
    ae_auc = auc_score(e_pos, e_neg)
    err_cal_pca = pca_recon_err(Xtr, Xcal, 8)
    err_inj_pca = pca_recon_err(Xtr, Xinj, 8)
    pca_auc = auc_score(err_inj_pca, err_cal_pca)

# ─── pass/fail ───────────────────────────────────────────────────────────
decay_ratio = final_train_loss / max(init_train_loss, 1e-12)
overfit_ratio = final_val_loss / max(final_train_loss, 1e-12)
c1_pass = 1 if decay_ratio < 0.5 else 0
c2_pass = 1 if overfit_ratio <= 3.0 else 0
c3_pass = 1 if c3_ok_frac >= 0.8 else 0
if c4_inject_n > 0:
    c4_pass = 1 if c4_inject_median_z >= Z_THRESHOLD else 0
else:
    c4_pass = -1  # not-applicable
c5_pass = 1 if c5_reeval_flag_frac < 0.5 else 0

verdict = 'FAIL'
core_ok = (c1_pass == 1 and c2_pass == 1)
calibrators = [c3_pass, c5_pass] + ([c4_pass] if c4_pass != -1 else [])
all_calibrators_ok = all(x == 1 for x in calibrators)
n_calibrator_fail = sum(1 for x in calibrators if x == 0)
if core_ok and all_calibrators_ok:
    verdict = 'PASS'
elif core_ok and n_calibrator_fail == 1:
    verdict = 'PARTIAL'
else:
    verdict = 'FAIL'

# ─── write dump ──────────────────────────────────────────────────────────
def x1000(v):
    if v != v:  # NaN
        return -2147483647
    if v == float('inf') or v == float('-inf'):
        return -2147483647
    return int(round(v * 1000.0))

with open(out_path, 'w') as f:
    f.write('schema=eeg_anom_ae_v1\n')
    f.write('mode=' + mode + '\n')
    f.write('kind=' + (src if mode == 'selftest' else 'real') + '\n')
    f.write('n_baseline=' + str(int(n_base)) + '\n')
    f.write('n_train=' + str(int(Xtr.shape[0])) + '\n')
    f.write('n_val=' + str(int(Xva.shape[0])) + '\n')
    f.write('n_calib=' + str(int(Xcal.shape[0])) + '\n')
    f.write('n_inject=' + str(int(c4_inject_n)) + '\n')
    f.write('feature_dim=' + str(int(FEATURE_DIM)) + '\n')
    f.write('bottleneck_dim=' + str(int(BOTTLENECK_DIM)) + '\n')
    f.write('epochs_run=' + str(int(len(history))) + '\n')
    f.write('init_train_loss_x1000=' + str(x1000(init_train_loss)) + '\n')
    f.write('final_train_loss_x1000=' + str(x1000(final_train_loss)) + '\n')
    f.write('final_val_loss_x1000=' + str(x1000(final_val_loss)) + '\n')
    f.write('decay_ratio_x1000=' + str(x1000(decay_ratio)) + '\n')
    f.write('overfit_ratio_x1000=' + str(x1000(overfit_ratio)) + '\n')
    f.write('mu_err_x1000=' + str(x1000(mu_e)) + '\n')
    f.write('sigma_err_x1000=' + str(x1000(sigma_e)) + '\n')
    f.write('c3_ok_frac_x1000=' + str(x1000(c3_ok_frac)) + '\n')
    f.write('c4_inject_median_z_x1000=' + str(x1000(c4_inject_median_z)) + '\n')
    f.write('c4_inject_flag_frac_x1000=' + str(x1000(c4_inject_flag_frac)) + '\n')
    f.write('c5_reeval_flag_frac_x1000=' + str(x1000(c5_reeval_flag_frac)) + '\n')
    f.write('ae_auc_x1000=' + str(x1000(ae_auc)) + '\n')
    f.write('pca_auc_x1000=' + str(x1000(pca_auc)) + '\n')
    f.write('c1_pass=' + str(int(c1_pass)) + '\n')
    f.write('c2_pass=' + str(int(c2_pass)) + '\n')
    f.write('c3_pass=' + str(int(c3_pass)) + '\n')
    f.write('c4_pass=' + str(int(c4_pass)) + '\n')
    f.write('c5_pass=' + str(int(c5_pass)) + '\n')
    f.write('verdict=' + verdict + '\n')

print('OK verdict=' + verdict + ' c1=' + str(c1_pass) + ' c2=' + str(c2_pass)
      + ' c3=' + str(c3_pass) + ' c4=' + str(c4_pass) + ' c5=' + str(c5_pass))
