#!/usr/bin/env python3
# clm_eeg_hjorth_real helper — auto-generated by anima-clm-eeg/tool/clm_eeg_hjorth_real.hexa
# raw#9 OK: /tmp-style transient (state/.hjorth_helper.py).
# raw#37: re-written every invocation.
# raw#82: darwin-native venv-eeg python; no remote dispatch.
import sys, os, math
try:
    import numpy as np
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n'); sys.exit(10)

if len(sys.argv) < 4:
    sys.stderr.write('usage: helper <mode> <input_or_kind> <out.txt>\n'); sys.exit(2)

mode, src, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

def load_eeg16(path):
    a = np.load(path, allow_pickle=False)
    if a.ndim != 2:
        raise RuntimeError('expected 2-D, got ndim=' + str(a.ndim))
    rows, cols = a.shape
    if rows == 16: return a, 16, cols
    if cols == 16: return a.T, 16, rows
    if rows >= 32 and cols > rows: return a[1:17, :], 16, cols
    if cols >= 32 and rows > cols: return a.T[1:17, :], 16, rows
    raise RuntimeError('cannot infer 16-ch layout from ' + str(a.shape))

def hjorth(x):
    x = np.asarray(x, dtype=np.float64)
    activity = float(np.var(x))
    if activity == 0.0:
        return 0.0, 0.0, 0.0
    d1 = np.diff(x)
    var_d1 = float(np.var(d1))
    if var_d1 == 0.0 or activity == 0.0:
        return activity, 0.0, 0.0
    mobility = math.sqrt(var_d1 / activity)
    if mobility == 0.0:
        return activity, mobility, 0.0
    d2 = np.diff(d1)
    var_d2 = float(np.var(d2))
    if var_d1 == 0.0:
        return activity, mobility, 0.0
    mobility_d1 = math.sqrt(var_d2 / var_d1)
    complexity = mobility_d1 / mobility
    return activity, mobility, complexity

if mode == 'selftest':
    kind = src
    n = 60 * 125
    rng = np.random.RandomState(11)
    eeg = np.zeros((16, n), dtype=np.float64)
    if kind == 'const':
        pass
    elif kind == 'white':
        for ch in range(16):
            eeg[ch, :] = rng.normal(0, 1, size=n)
    elif kind == 'sine':
        t = np.arange(n) / 125.0
        for ch in range(16):
            eeg[ch, :] = np.sin(2 * np.pi * 10.0 * t)
    elif kind == 'drift':
        # very-low-frequency drift -- mobility collapses
        t = np.arange(n) / 125.0
        for ch in range(16):
            eeg[ch, :] = np.sin(2 * np.pi * 0.05 * t)
    else:
        sys.stderr.write('unknown selftest kind: ' + kind + '\n'); sys.exit(3)
    n_ch, n_samp = 16, n
elif mode == 'real':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n'); sys.exit(4)
    eeg, n_ch, n_samp = load_eeg16(src)
else:
    sys.stderr.write('unknown mode: ' + mode + '\n'); sys.exit(2)

acts, mobs, cpxs = [], [], []
for ch in range(n_ch):
    a_, m_, c_ = hjorth(eeg[ch, :])
    acts.append(a_); mobs.append(m_); cpxs.append(c_)

act_mean = float(np.mean(acts))
mob_mean = float(np.mean(mobs))
cpx_mean = float(np.mean(cpxs))
# O1, O2 specific
mob_o1 = mobs[6] if n_ch > 6 else 0.0
cpx_o1 = cpxs[6] if n_ch > 6 else 0.0
mob_o2 = mobs[7] if n_ch > 7 else 0.0
cpx_o2 = cpxs[7] if n_ch > 7 else 0.0

with open(out_path, 'w') as f:
    f.write('schema=hjorth_v1\n')
    f.write('n_ch=' + str(int(n_ch)) + '\n')
    f.write('n_samp=' + str(int(n_samp)) + '\n')
    # activity scale varies enormously across raw vs filtered vs ICA --
    # report as natural log fixed-point to keep within int range.
    if act_mean > 0:
        log_act_x1000 = int(round(math.log10(act_mean) * 1000))
    else:
        log_act_x1000 = -2147483647
    f.write('log10_activity_mean_x1000=' + str(log_act_x1000) + '\n')
    f.write('mobility_mean_x1000=' + str(int(round(mob_mean * 1000))) + '\n')
    f.write('complexity_mean_x1000=' + str(int(round(cpx_mean * 1000))) + '\n')
    f.write('mobility_o1_x1000=' + str(int(round(mob_o1 * 1000))) + '\n')
    f.write('complexity_o1_x1000=' + str(int(round(cpx_o1 * 1000))) + '\n')
    f.write('mobility_o2_x1000=' + str(int(round(mob_o2 * 1000))) + '\n')
    f.write('complexity_o2_x1000=' + str(int(round(cpx_o2 * 1000))) + '\n')

print('OK cpx=' + ('%.4f' % cpx_mean) + ' mob=' + ('%.4f' % mob_mean))
