#!/usr/bin/env python3
# clm_eeg_pe_real helper — auto-generated by anima-clm-eeg/tool/clm_eeg_pe_real.hexa
# raw#9 OK: /tmp-style transient (state/.pe_helper.py).
# raw#37: re-written every invocation.
# raw#82: darwin-native venv-eeg python; no remote dispatch.
import sys, os, math
try:
    import numpy as np
except Exception as e:
    sys.stderr.write('import-failed: ' + repr(e) + '\n'); sys.exit(10)

if len(sys.argv) < 4:
    sys.stderr.write('usage: helper <mode> <input_or_kind> <out.txt>\n'); sys.exit(2)

mode, src, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
M = 3
TAU = 1
SCALES = [1, 2, 5, 10]

def load_eeg16(path):
    a = np.load(path, allow_pickle=False)
    if a.ndim != 2:
        raise RuntimeError('expected 2-D, got ndim=' + str(a.ndim))
    rows, cols = a.shape
    if rows == 16: return a, 16, cols
    if cols == 16: return a.T, 16, rows
    if rows >= 32 and cols > rows: return a[1:17, :], 16, cols
    if cols >= 32 and rows > cols: return a.T[1:17, :], 16, rows
    raise RuntimeError('cannot infer 16-ch layout from ' + str(a.shape))

def coarse_grain(x, s):
    if s <= 1: return x
    n = len(x) // s
    if n <= 0: return np.array([], dtype=np.float64)
    return x[: n * s].reshape(n, s).mean(axis=1)

def permutation_entropy(x, m=3, tau=1):
    n = len(x)
    L = n - (m - 1) * tau
    if L <= 0: return 0.0
    # Build ordinal patterns (encode each via factorial-radix index 0..m!-1)
    # for m=3 the 6 permutations of indices (0,1,2) map to a unique int 0..5.
    counts = {}
    for i in range(L):
        w = x[i:i + m * tau:tau]
        # argsort returns the indices that would sort w ascending; this is
        # the canonical Bandt-Pompe ordinal pattern.
        perm = tuple(int(v) for v in np.argsort(w, kind='stable'))
        counts[perm] = counts.get(perm, 0) + 1
    total = float(L)
    H = 0.0
    for c in counts.values():
        p = c / total
        if p > 0.0:
            H -= p * math.log(p)
    Hmax = math.log(math.factorial(m))
    if Hmax <= 0: return 0.0
    return H / Hmax

if mode == 'selftest':
    kind = src
    n = 60 * 125  # 60 s @ 125 Hz
    rng = np.random.RandomState(7)
    eeg = np.zeros((16, n), dtype=np.float64)
    if kind == 'const':
        # constant signal → PE should be 0
        pass
    elif kind == 'white':
        for ch in range(16):
            eeg[ch, :] = rng.normal(0, 1, size=n)
    elif kind == 'sine':
        # Low-PE counter-example: strictly monotonic ramp. Every length-m
        # ordinal window sees the SAME ascending pattern (0,1,...,m-1), so
        # the empirical permutation distribution is degenerate (1 of m!) and
        # PE collapses to 0 (Bandt-Pompe 2002 sec III, monotonic example).
        # NOTE: a pure 10 Hz sine on a 125 Hz grid is NOT a low-PE
        # counter-example -- it visits many phase offsets and yields PE
        # approx 0.7. We use a ramp to exercise F3 cleanly.
        for ch in range(16):
            eeg[ch, :] = np.arange(n, dtype=np.float64) + ch * 0.5
    else:
        sys.stderr.write('unknown selftest kind: ' + kind + '\n'); sys.exit(3)
    n_ch, n_samp = 16, n
elif mode == 'real':
    if not os.path.isfile(src):
        sys.stderr.write('not-found: ' + src + '\n'); sys.exit(4)
    eeg, n_ch, n_samp = load_eeg16(src)
else:
    sys.stderr.write('unknown mode: ' + mode + '\n'); sys.exit(2)

# Per (channel, scale) PE
pe_per_ch_scale = np.zeros((n_ch, len(SCALES)), dtype=np.float64)
for ch in range(n_ch):
    x = np.asarray(eeg[ch, :], dtype=np.float64)
    for j, s in enumerate(SCALES):
        cg = coarse_grain(x, s)
        if len(cg) <= M * TAU:
            pe_per_ch_scale[ch, j] = float('nan')
        else:
            pe_per_ch_scale[ch, j] = permutation_entropy(cg, m=M, tau=TAU)

# Means
finite = ~np.isnan(pe_per_ch_scale)
pe_mean_overall = float(np.nanmean(pe_per_ch_scale))
pe_mean_scale1  = float(np.nanmean(pe_per_ch_scale[:, 0]))
pe_mean_scale2  = float(np.nanmean(pe_per_ch_scale[:, 1]))
pe_mean_scale5  = float(np.nanmean(pe_per_ch_scale[:, 2]))
pe_mean_scale10 = float(np.nanmean(pe_per_ch_scale[:, 3]))
# O1, O2 specifically
pe_o1_scale1 = float(pe_per_ch_scale[6, 0]) if n_ch > 6 else float('nan')
pe_o2_scale1 = float(pe_per_ch_scale[7, 0]) if n_ch > 7 else float('nan')

with open(out_path, 'w') as f:
    f.write('schema=pe_v1\n')
    f.write('n_ch=' + str(int(n_ch)) + '\n')
    f.write('n_samp=' + str(int(n_samp)) + '\n')
    f.write('embed_dim=' + str(M) + '\n')
    f.write('embed_tau=' + str(TAU) + '\n')
    f.write('scales=1,2,5,10\n')
    f.write('pe_mean_overall_x1000=' + str(int(round(pe_mean_overall * 1000))) + '\n')
    f.write('pe_mean_scale1_x1000=' + str(int(round(pe_mean_scale1 * 1000))) + '\n')
    f.write('pe_mean_scale2_x1000=' + str(int(round(pe_mean_scale2 * 1000))) + '\n')
    f.write('pe_mean_scale5_x1000=' + str(int(round(pe_mean_scale5 * 1000))) + '\n')
    f.write('pe_mean_scale10_x1000=' + str(int(round(pe_mean_scale10 * 1000))) + '\n')
    f.write('pe_o1_scale1_x1000=' + str(int(round(pe_o1_scale1 * 1000))) + '\n')
    f.write('pe_o2_scale1_x1000=' + str(int(round(pe_o2_scale1 * 1000))) + '\n')

print('OK pe_mean=' + ('%.4f' % pe_mean_overall))
